-- Happy Paws - Ventas con múltiples productos + subtotal/IGV
--
-- Ejecutar UNA sola vez sobre la base de datos (Supabase / PostgreSQL) que ya
-- tenga aplicado docs/supabase-migration-new-ids.sql (columnas id_venta,
-- id_producto, etc.). Es idempotente: se puede correr más de una vez sin
-- romper nada. Sigue el mismo patrón que
-- docs/supabase-migration-compras-detalle.sql.

BEGIN;

-- 1) Nuevas columnas de cabecera en "ventas" para guardar el desglose.
ALTER TABLE ventas
    ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE ventas
    ADD COLUMN IF NOT EXISTS igv NUMERIC(12,2) NOT NULL DEFAULT 0;

-- 2) Tabla de detalle: un producto, cantidad y precio unitario por línea.
CREATE TABLE IF NOT EXISTS venta_detalles (
    id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_venta BIGINT NOT NULL,

    id_producto BIGINT NOT NULL,

    cantidad INTEGER NOT NULL,

    precio_unitario NUMERIC(12,2) NOT NULL,

    subtotal NUMERIC(12,2)
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_venta_detalles_venta
        FOREIGN KEY (id_venta)
        REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_venta_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_venta_detalles_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_venta_detalles_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT uq_venta_producto
        UNIQUE (id_venta, id_producto)
);

CREATE INDEX IF NOT EXISTS idx_venta_detalles_producto_id
    ON venta_detalles(id_producto);

CREATE INDEX IF NOT EXISTS idx_venta_detalles_venta_id
    ON venta_detalles(id_venta);

COMMIT;
