-- Happy Paws - Compras con múltiples productos + subtotal/IGV
--
-- Ejecutar UNA sola vez sobre la base de datos (Supabase / PostgreSQL) que ya
-- tenga aplicado docs/supabase-migration-new-ids.sql (columnas id_compra,
-- id_producto, id_detalle_compra, etc.). Es idempotente: se puede correr más
-- de una vez sin romper nada.

BEGIN;

-- 1) Nuevas columnas de cabecera en "compras" para guardar el desglose.
ALTER TABLE compras
    ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE compras
    ADD COLUMN IF NOT EXISTS igv NUMERIC(12,2) NOT NULL DEFAULT 0;

-- 2) Por si la tabla de detalle todavía no existe en este entorno.
CREATE TABLE IF NOT EXISTS compra_detalles (
    id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_compra BIGINT NOT NULL,

    id_producto BIGINT NOT NULL,

    cantidad INTEGER NOT NULL,

    precio_unitario NUMERIC(12,2) NOT NULL,

    subtotal NUMERIC(12,2)
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_compra_detalles_compra
        FOREIGN KEY (id_compra)
        REFERENCES compras(id_compra)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_compra_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compra_detalles_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_compra_detalles_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT uq_compra_producto
        UNIQUE (id_compra, id_producto)
);

CREATE INDEX IF NOT EXISTS idx_compra_detalles_producto_id
    ON compra_detalles(id_producto);

CREATE INDEX IF NOT EXISTS idx_compra_detalles_compra_id
    ON compra_detalles(id_compra);

COMMIT;
