-- ============================================================
-- HAPPY PAWS - VETERINARIA
-- ESQUEMA CORREGIDO PARA EL PROYECTO SPRING BOOT
-- PostgreSQL / Supabase
-- ============================================================
-- IMPORTANTE:
-- Este archivo reemplaza el SQL anterior que tenía dos
-- incompatibilidades principales:
--   1) appointments.fecha -> appointments.fecha_hora
--   2) appointments.veterinario_id ahora referencia users.id
-- También incluye password_reset_tokens y un esquema de
-- permissions compatible con DataInitializer/Permission.java.
-- ============================================================

DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS compras CASCADE;
DROP TABLE IF EXISTS comprobante_series CASCADE;
DROP TABLE IF EXISTS comprobante_tipos CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS afectacion_tipos CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS historial_mascotas CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS documento_tipos CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;

-- ============================================================
-- 1. TIPOS DE DOCUMENTO
-- ============================================================
CREATE TABLE documento_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);
CREATE INDEX idx_documento_tipos_codigo ON documento_tipos(codigo);

-- ============================================================
-- 2. ROLES
-- ============================================================
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150),
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_roles_name ON roles(name);
CREATE INDEX idx_roles_enabled ON roles(enabled);

-- ============================================================
-- 3. USERS
-- ============================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_users_email ON users(email);

-- ============================================================
-- 4. USER ROLES
-- ============================================================
-- user_id es PRIMARY KEY (no solo parte de una PK compuesta con role_id):
-- esto es lo que garantiza a nivel de base de datos que un usuario
-- nunca pueda tener más de un rol asignado al mismo tiempo.
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

-- ============================================================
-- 5. MODULES (CATÁLOGO DEL RBAC)
-- Cada permiso pertenece obligatoriamente a un módulo.
-- ============================================================
CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(150),
    icon VARCHAR(100),
    route VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0
);
CREATE INDEX idx_modules_code ON modules(code);
CREATE INDEX idx_modules_enabled ON modules(enabled);
CREATE INDEX idx_modules_display_order ON modules(display_order);

-- ============================================================
-- 6. PERMISSIONS
-- Entidad normalizada: código único + módulo obligatorio + acción.
-- ============================================================
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(150),
    action VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id)
        REFERENCES modules(id) ON DELETE RESTRICT,
    CONSTRAINT ck_permissions_action CHECK (action IN ('VIEW','CREATE','UPDATE','DELETE','EXPORT','ASSIGN'))
);
CREATE INDEX idx_permissions_module_id ON permissions(module_id);
CREATE INDEX idx_permissions_code ON permissions(code);
CREATE INDEX idx_permissions_action ON permissions(action);
CREATE INDEX idx_permissions_enabled ON permissions(enabled);

-- ============================================================
-- 7. ROLE PERMISSIONS
-- ============================================================
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES permissions(id) ON DELETE CASCADE
);
CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(permission_id);

-- ============================================================
-- 8. PASSWORD RESET TOKENS
-- ============================================================
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expiry_date ON password_reset_tokens(expiry_date);

-- ============================================================
-- 9. CLIENTES
-- ============================================================
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_codigo VARCHAR(20) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(30),
    email VARCHAR(150),
    CONSTRAINT fk_clientes_documento_tipo FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
);
CREATE INDEX idx_clientes_numero_documento ON clientes(numero_documento);
CREATE INDEX idx_clientes_documento_tipo ON clientes(documento_tipo_codigo);
CREATE INDEX idx_clientes_razon_social ON clientes(razon_social);

-- ============================================================
-- 10. PROVEEDORES
-- ============================================================
CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_codigo VARCHAR(20) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(30),
    email VARCHAR(150),
    CONSTRAINT fk_proveedores_documento_tipo FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
);
CREATE INDEX idx_proveedores_numero_documento ON proveedores(numero_documento);
CREATE INDEX idx_proveedores_documento_tipo ON proveedores(documento_tipo_codigo);
CREATE INDEX idx_proveedores_razon_social ON proveedores(razon_social);

-- ============================================================
-- 11. MASCOTAS
-- ============================================================
CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    especie VARCHAR(80) NOT NULL,
    raza VARCHAR(80),
    edad INT,
    cliente_id BIGINT NOT NULL,
    CONSTRAINT fk_pets_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(id) ON DELETE CASCADE
);
CREATE INDEX idx_pets_cliente_id ON pets(cliente_id);
CREATE INDEX idx_pets_nombre ON pets(nombre);

-- ============================================================
-- 12. CITAS
-- IMPORTANTE: coincide exactamente con Appointment.java.
-- veterinario_id referencia users porque Appointment.veterinario
-- es de tipo User, no una entidad Veterinario.
-- ============================================================
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    veterinario_id BIGINT,
    fecha_hora TIMESTAMP NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    CONSTRAINT fk_appointments_pet FOREIGN KEY (pet_id)
        REFERENCES pets(id) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_veterinario FOREIGN KEY (veterinario_id)
        REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_appointments_pet_id ON appointments(pet_id);
CREATE INDEX idx_appointments_cliente_id ON appointments(cliente_id);
CREATE INDEX idx_appointments_veterinario_id ON appointments(veterinario_id);
CREATE INDEX idx_appointments_fecha_hora ON appointments(fecha_hora);

-- ============================================================
-- 13. HISTORIAL DE MASCOTAS
-- ============================================================
CREATE TABLE historial_mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    appointment_id BIGINT,
    titulo VARCHAR(150) NOT NULL,
    detalle VARCHAR(1500) NOT NULL,
    diagnostico VARCHAR(500),
    tratamiento VARCHAR(500),
    fecha_registro DATE NOT NULL,
    fecha_expiracion DATE NOT NULL,
    archivo_original VARCHAR(255),
    archivo_guardado VARCHAR(255),
    archivo_tipo VARCHAR(120),
    archivo_tamanio BIGINT,
    CONSTRAINT fk_historial_pet FOREIGN KEY (pet_id)
        REFERENCES pets(id) ON DELETE CASCADE,
    CONSTRAINT fk_historial_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(id) ON DELETE SET NULL
);
CREATE INDEX idx_historial_pet_id ON historial_mascotas(pet_id);
CREATE INDEX idx_historial_fecha_registro ON historial_mascotas(fecha_registro);
CREATE INDEX idx_historial_fecha_expiracion ON historial_mascotas(fecha_expiracion);

-- ============================================================
-- 14. UNIDADES
-- ============================================================
CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);
CREATE INDEX idx_units_codigo ON units(codigo);

-- ============================================================
-- 15. TIPOS DE AFECTACIÓN
-- ============================================================
CREATE TABLE afectacion_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    letra VARCHAR(1) NOT NULL,
    porcentaje DECIMAL(5,2) NOT NULL
);
CREATE INDEX idx_afectacion_tipos_codigo ON afectacion_tipos(codigo);

-- ============================================================
-- 16. PRODUCTOS
-- ============================================================
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    unidad_id BIGINT NOT NULL,
    afectacion_tipo_id BIGINT NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    imagen VARCHAR(255),
    CONSTRAINT fk_productos_unidad FOREIGN KEY (unidad_id)
        REFERENCES units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_productos_afectacion FOREIGN KEY (afectacion_tipo_id)
        REFERENCES afectacion_tipos(id) ON DELETE RESTRICT
);
CREATE INDEX idx_productos_codigo ON productos(codigo);
CREATE INDEX idx_productos_nombre ON productos(nombre);
CREATE INDEX idx_productos_unidad_id ON productos(unidad_id);
CREATE INDEX idx_productos_afectacion_tipo_id ON productos(afectacion_tipo_id);

-- ============================================================
-- 17. TIPOS DE COMPROBANTE
-- ============================================================
CREATE TABLE comprobante_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);
CREATE INDEX idx_comprobante_tipos_codigo ON comprobante_tipos(codigo);

-- ============================================================
-- 18. SERIES DE COMPROBANTES
-- ============================================================
CREATE TABLE comprobante_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_tipo_codigo VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    correlativo INT NOT NULL,
    CONSTRAINT uk_comprobante_tipo_serie UNIQUE (comprobante_tipo_codigo, serie),
    CONSTRAINT fk_comprobante_series_tipo FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
);
CREATE INDEX idx_comprobante_series_tipo ON comprobante_series(comprobante_tipo_codigo);
CREATE INDEX idx_comprobante_series_serie ON comprobante_series(serie);

-- ============================================================
-- 19. COMPRAS
-- ============================================================
CREATE TABLE compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    proveedor_id BIGINT NOT NULL,
    comprobante_tipo_codigo VARCHAR(20) NOT NULL,
    forma_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',
    total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_compras_proveedor FOREIGN KEY (proveedor_id)
        REFERENCES proveedores(id) ON DELETE RESTRICT,
    CONSTRAINT fk_compras_comprobante_tipo FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
);
CREATE INDEX idx_compras_numero ON compras(numero);
CREATE INDEX idx_compras_fecha ON compras(fecha);
CREATE INDEX idx_compras_proveedor_id ON compras(proveedor_id);
CREATE INDEX idx_compras_estado ON compras(estado);

-- ============================================================
-- 20. VENTAS
-- ============================================================
CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    cliente_id BIGINT NOT NULL,
    forma_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',
    total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_ventas_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(id) ON DELETE RESTRICT
);
CREATE INDEX idx_ventas_numero ON ventas(numero);
CREATE INDEX idx_ventas_fecha ON ventas(fecha);
CREATE INDEX idx_ventas_cliente_id ON ventas(cliente_id);
CREATE INDEX idx_ventas_estado ON ventas(estado);

-- ============================================================
-- 21. CONFIGURACIÓN
-- ============================================================
CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value VARCHAR(255) NOT NULL
);
CREATE INDEX idx_system_settings_key ON system_settings(setting_key);

-- ============================================================
-- DATOS INICIALES
-- ============================================================
INSERT INTO documento_tipos (codigo, descripcion) VALUES
('CC', 'Cédula de Ciudadanía'),
('CE', 'Cédula de Extranjería'),
('NIT', 'Número de Identificación Tributaria'),
('PA', 'Pasaporte')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO roles (name, description) VALUES
('ADMIN', 'Administrador del sistema'),
('VETERINARIO', 'Profesional veterinario'),
('RECEPCIONISTA', 'Personal de recepción'),
('CLIENTE', 'Cliente de la veterinaria')
ON CONFLICT (name) DO NOTHING;

INSERT INTO modules (code, name, description, icon, route, display_order) VALUES
('DASHBOARD', 'Dashboard', 'Panel principal', 'bi-speedometer2', '/dashboard', 1),
('CITAS', 'Citas', 'Agenda y gestión de citas', 'bi-calendar-check', '/citas', 2),
('MASCOTAS', 'Mascotas', 'Registro y gestión de mascotas', 'bi-heart-fill', '/mascotas', 3),
('CLIENTES', 'Clientes', 'Gestión de clientes', 'bi-people-fill', '/clientes', 4),
('PRODUCTOS', 'Productos', 'Inventario y catálogo de productos', 'bi-box-seam', '/productos', 5),
('COMPRAS', 'Compras', 'Compras y abastecimiento', 'bi-cart-check', '/compras', 6),
('VENTAS', 'Ventas', 'Ventas y facturación', 'bi-cash-coin', '/ventas', 7),
('PROVEEDORES', 'Proveedores', 'Gestión de proveedores', 'bi-truck', '/proveedores', 8),
('HISTORIAL', 'Historial clínico', 'Historial médico de mascotas', 'bi-file-medical', '/historial', 9),
('USUARIOS', 'Usuarios', 'Administración de usuarios', 'bi-person-gear', '/usuarios', 10),
('ROLES', 'Roles', 'Administración de roles y permisos', 'bi-shield-lock', '/roles', 11),
('REPORTES', 'Reportes', 'Reportes del sistema', 'bi-bar-chart', '/reportes', 12),
('CONFIGURACION', 'Configuración', 'Configuración general del sistema', 'bi-gear', '/admin', 13),
('CONFIGURACION_COMPROBANTES', 'Configuración de comprobantes', 'Configuración de comprobantes', 'bi-receipt', '/configuracion/comprobantes', 14),
('CONFIGURACION_DOCUMENTOS', 'Configuración de documentos', 'Configuración de documentos', 'bi-file-text', '/configuracion/documentos', 15),
('CONFIGURACION_UNIDADES', 'Configuración de unidades', 'Configuración de unidades', 'bi-rulers', '/configuracion/unidades', 16),
('CONFIGURACION_AFECTACIONES', 'Configuración de afectaciones', 'Configuración de afectaciones', 'bi-percent', '/configuracion/afectaciones', 17)
ON CONFLICT (code) DO NOTHING;

-- Catálogo normalizado de permisos.
INSERT INTO permissions (code, name, description, action, module_id) VALUES
('DASHBOARD_VER', 'DASHBOARD_VER', 'Ver el dashboard', 'VIEW', (SELECT id FROM modules WHERE code = 'DASHBOARD')),
('DASHBOARD_CLIENTE_VER', 'DASHBOARD_CLIENTE_VER', 'Ver dashboard de cliente', 'VIEW', (SELECT id FROM modules WHERE code = 'DASHBOARD')),
('CITAS_VER', 'CITAS_VER', 'Ver citas', 'VIEW', (SELECT id FROM modules WHERE code = 'CITAS')),
('CITAS_CREAR', 'CITAS_CREAR', 'Crear citas', 'CREATE', (SELECT id FROM modules WHERE code = 'CITAS')),
('CITAS_EDITAR', 'CITAS_EDITAR', 'Editar citas', 'UPDATE', (SELECT id FROM modules WHERE code = 'CITAS')),
('CITAS_ELIMINAR', 'CITAS_ELIMINAR', 'Eliminar citas', 'DELETE', (SELECT id FROM modules WHERE code = 'CITAS')),
('MASCOTAS_VER', 'MASCOTAS_VER', 'Ver mascotas', 'VIEW', (SELECT id FROM modules WHERE code = 'MASCOTAS')),
('MASCOTAS_CREAR', 'MASCOTAS_CREAR', 'Crear mascotas', 'CREATE', (SELECT id FROM modules WHERE code = 'MASCOTAS')),
('MASCOTAS_EDITAR', 'MASCOTAS_EDITAR', 'Editar mascotas', 'UPDATE', (SELECT id FROM modules WHERE code = 'MASCOTAS')),
('MASCOTAS_ELIMINAR', 'MASCOTAS_ELIMINAR', 'Eliminar mascotas', 'DELETE', (SELECT id FROM modules WHERE code = 'MASCOTAS')),
('CLIENTES_VER', 'CLIENTES_VER', 'Ver clientes', 'VIEW', (SELECT id FROM modules WHERE code = 'CLIENTES')),
('CLIENTES_CREAR', 'CLIENTES_CREAR', 'Crear clientes', 'CREATE', (SELECT id FROM modules WHERE code = 'CLIENTES')),
('CLIENTES_EDITAR', 'CLIENTES_EDITAR', 'Editar clientes', 'UPDATE', (SELECT id FROM modules WHERE code = 'CLIENTES')),
('CLIENTES_ELIMINAR', 'CLIENTES_ELIMINAR', 'Eliminar clientes', 'DELETE', (SELECT id FROM modules WHERE code = 'CLIENTES')),
('PRODUCTOS_VER', 'PRODUCTOS_VER', 'Ver productos', 'VIEW', (SELECT id FROM modules WHERE code = 'PRODUCTOS')),
('PRODUCTOS_CREAR', 'PRODUCTOS_CREAR', 'Crear productos', 'CREATE', (SELECT id FROM modules WHERE code = 'PRODUCTOS')),
('PRODUCTOS_EDITAR', 'PRODUCTOS_EDITAR', 'Editar productos', 'UPDATE', (SELECT id FROM modules WHERE code = 'PRODUCTOS')),
('PRODUCTOS_ELIMINAR', 'PRODUCTOS_ELIMINAR', 'Eliminar productos', 'DELETE', (SELECT id FROM modules WHERE code = 'PRODUCTOS')),
('COMPRAS_VER', 'COMPRAS_VER', 'Ver compras', 'VIEW', (SELECT id FROM modules WHERE code = 'COMPRAS')),
('COMPRAS_CREAR', 'COMPRAS_CREAR', 'Crear compras', 'CREATE', (SELECT id FROM modules WHERE code = 'COMPRAS')),
('COMPRAS_EDITAR', 'COMPRAS_EDITAR', 'Editar compras', 'UPDATE', (SELECT id FROM modules WHERE code = 'COMPRAS')),
('COMPRAS_ELIMINAR', 'COMPRAS_ELIMINAR', 'Eliminar compras', 'DELETE', (SELECT id FROM modules WHERE code = 'COMPRAS')),
('VENTAS_VER', 'VENTAS_VER', 'Ver ventas', 'VIEW', (SELECT id FROM modules WHERE code = 'VENTAS')),
('VENTAS_CREAR', 'VENTAS_CREAR', 'Crear ventas', 'CREATE', (SELECT id FROM modules WHERE code = 'VENTAS')),
('VENTAS_EDITAR', 'VENTAS_EDITAR', 'Editar ventas', 'UPDATE', (SELECT id FROM modules WHERE code = 'VENTAS')),
('VENTAS_ELIMINAR', 'VENTAS_ELIMINAR', 'Eliminar ventas', 'DELETE', (SELECT id FROM modules WHERE code = 'VENTAS')),
('PROVEEDORES_VER', 'PROVEEDORES_VER', 'Ver proveedores', 'VIEW', (SELECT id FROM modules WHERE code = 'PROVEEDORES')),
('PROVEEDORES_CREAR', 'PROVEEDORES_CREAR', 'Crear proveedores', 'CREATE', (SELECT id FROM modules WHERE code = 'PROVEEDORES')),
('PROVEEDORES_EDITAR', 'PROVEEDORES_EDITAR', 'Editar proveedores', 'UPDATE', (SELECT id FROM modules WHERE code = 'PROVEEDORES')),
('PROVEEDORES_ELIMINAR', 'PROVEEDORES_ELIMINAR', 'Eliminar proveedores', 'DELETE', (SELECT id FROM modules WHERE code = 'PROVEEDORES')),
('HISTORIAL_VER', 'HISTORIAL_VER', 'Ver historial clínico', 'VIEW', (SELECT id FROM modules WHERE code = 'HISTORIAL')),
('HISTORIAL_CREAR', 'HISTORIAL_CREAR', 'Crear historial clínico', 'CREATE', (SELECT id FROM modules WHERE code = 'HISTORIAL')),
('HISTORIAL_EDITAR', 'HISTORIAL_EDITAR', 'Editar historial clínico', 'UPDATE', (SELECT id FROM modules WHERE code = 'HISTORIAL')),
('HISTORIAL_ELIMINAR', 'HISTORIAL_ELIMINAR', 'Eliminar historial clínico', 'DELETE', (SELECT id FROM modules WHERE code = 'HISTORIAL')),
('REPORTES_VER', 'REPORTES_VER', 'Ver reportes', 'VIEW', (SELECT id FROM modules WHERE code = 'REPORTES')),
('REPORTES_EXPORTAR', 'REPORTES_EXPORTAR', 'Exportar reportes', 'EXPORT', (SELECT id FROM modules WHERE code = 'REPORTES')),
('USUARIOS_VER', 'USUARIOS_VER', 'Ver usuarios', 'VIEW', (SELECT id FROM modules WHERE code = 'USUARIOS')),
('USUARIOS_CREAR', 'USUARIOS_CREAR', 'Crear usuarios', 'CREATE', (SELECT id FROM modules WHERE code = 'USUARIOS')),
('USUARIOS_EDITAR', 'USUARIOS_EDITAR', 'Editar usuarios', 'UPDATE', (SELECT id FROM modules WHERE code = 'USUARIOS')),
('USUARIOS_ELIMINAR', 'USUARIOS_ELIMINAR', 'Eliminar usuarios', 'DELETE', (SELECT id FROM modules WHERE code = 'USUARIOS')),
('ROLES_VER', 'ROLES_VER', 'Ver roles', 'VIEW', (SELECT id FROM modules WHERE code = 'ROLES')),
('ROLES_CREAR', 'ROLES_CREAR', 'Crear roles', 'CREATE', (SELECT id FROM modules WHERE code = 'ROLES')),
('ROLES_EDITAR', 'ROLES_EDITAR', 'Editar roles', 'UPDATE', (SELECT id FROM modules WHERE code = 'ROLES')),
('ROLES_ELIMINAR', 'ROLES_ELIMINAR', 'Eliminar roles', 'DELETE', (SELECT id FROM modules WHERE code = 'ROLES')),
('ROLES_ASIGNAR', 'ROLES_ASIGNAR', 'Asignar roles a usuarios', 'ASSIGN', (SELECT id FROM modules WHERE code = 'ROLES')),
('PERMISOS_VER', 'PERMISOS_VER', 'Ver permisos', 'VIEW', (SELECT id FROM modules WHERE code = 'ROLES')),
('PERMISOS_ASIGNAR', 'PERMISOS_ASIGNAR', 'Asignar permisos', 'ASSIGN', (SELECT id FROM modules WHERE code = 'ROLES')),
('CONFIGURACION_COMPROBANTES', 'CONFIGURACION_COMPROBANTES', 'Administrar comprobantes', 'VIEW', (SELECT id FROM modules WHERE code = 'CONFIGURACION_COMPROBANTES')),
('CONFIGURACION_DOCUMENTOS', 'CONFIGURACION_DOCUMENTOS', 'Administrar tipos de documento', 'VIEW', (SELECT id FROM modules WHERE code = 'CONFIGURACION_DOCUMENTOS')),
('CONFIGURACION_UNIDADES', 'CONFIGURACION_UNIDADES', 'Administrar unidades', 'VIEW', (SELECT id FROM modules WHERE code = 'CONFIGURACION_UNIDADES')),
('CONFIGURACION_AFECTACIONES', 'CONFIGURACION_AFECTACIONES', 'Administrar afectaciones', 'VIEW', (SELECT id FROM modules WHERE code = 'CONFIGURACION_AFECTACIONES'))
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, action=EXCLUDED.action, module_id=EXCLUDED.module_id, enabled=TRUE;

-- ADMIN: todos los permisos
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;

-- VETERINARIO
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r JOIN permissions p ON p.name IN (
    'DASHBOARD_VER',
    'CITAS_VER', 'CITAS_CREAR', 'CITAS_EDITAR',
    'MASCOTAS_VER', 'MASCOTAS_CREAR', 'MASCOTAS_EDITAR',
    'CLIENTES_VER', 'PRODUCTOS_VER',
    'VENTAS_VER', 'VENTAS_CREAR',
    'HISTORIAL_VER', 'HISTORIAL_CREAR', 'HISTORIAL_EDITAR'
)
WHERE r.name = 'VETERINARIO'
ON CONFLICT DO NOTHING;

-- RECEPCIONISTA
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r JOIN permissions p ON p.name IN (
    'DASHBOARD_VER',
    'CITAS_VER', 'CITAS_CREAR', 'CITAS_EDITAR', 'CITAS_ELIMINAR',
    'CLIENTES_VER', 'CLIENTES_CREAR', 'CLIENTES_EDITAR',
    'MASCOTAS_VER', 'MASCOTAS_CREAR', 'MASCOTAS_EDITAR',
    'PRODUCTOS_VER',
    'COMPRAS_VER', 'COMPRAS_CREAR', 'COMPRAS_EDITAR',
    'PROVEEDORES_VER', 'PROVEEDORES_CREAR', 'PROVEEDORES_EDITAR',
    'VENTAS_VER', 'VENTAS_CREAR'
)
WHERE r.name = 'RECEPCIONISTA'
ON CONFLICT DO NOTHING;

-- CLIENTE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r JOIN permissions p ON p.name IN (
    'DASHBOARD_CLIENTE_VER',
    'CITAS_VER', 'CITAS_CREAR',
    'MASCOTAS_VER', 'CLIENTES_VER', 'HISTORIAL_VER', 'VENTAS_VER'
)
WHERE r.name = 'CLIENTE'
ON CONFLICT DO NOTHING;

-- ============================================================
-- DATOS DE PRUEBA: CLIENTES
-- ============================================================
INSERT INTO clientes (documento_tipo_codigo, numero_documento, razon_social, direccion, telefono, email) VALUES
('CC', '10000001', 'Cliente de Prueba', 'Calle 1 # 2-3', '3000000000', 'cliente.prueba@happypaws.com'),
('CC', '10000002', 'Juan Pérez García', 'Carrera 5 # 10-15', '3105551234', 'juan.perez@email.com'),
('NIT', '900123456', 'Peluquería Canina S.A.S', 'Calle Principal 123', '3155559876', 'contacto@pelucanina.com')
ON CONFLICT (numero_documento) DO NOTHING;

-- ============================================================
-- PROVEEDORES
-- ============================================================
INSERT INTO proveedores (documento_tipo_codigo, numero_documento, razon_social, direccion, telefono, email) VALUES
('NIT', '800456789', 'Distribuidor Veterinario Nacional', 'Calle Industrial 456', '3165554321', 'ventas@distribvet.com'),
('NIT', '800987654', 'Importadora de Medicinas', 'Av. Comercial 789', '3105552468', 'info@importmedicinas.com')
ON CONFLICT (numero_documento) DO NOTHING;

-- ============================================================
-- MASCOTAS
-- ============================================================
INSERT INTO pets (nombre, especie, raza, edad, cliente_id) VALUES
('Max', 'Perro', 'Golden Retriever', 3, (SELECT id FROM clientes WHERE numero_documento = '10000001')),
('Luna', 'Gato', 'Persa', 2, (SELECT id FROM clientes WHERE numero_documento = '10000001')),
('Rocky', 'Perro', 'Pastor Alemán', 5, (SELECT id FROM clientes WHERE numero_documento = '10000002'));

-- ============================================================
-- CITAS DE PRUEBA
-- veterinario_id queda NULL porque los usuarios veterinarios
-- se crean de forma segura desde DataInitializer con BCrypt.
-- ============================================================
INSERT INTO appointments (pet_id, cliente_id, veterinario_id, fecha_hora, motivo) VALUES
((SELECT id FROM pets WHERE nombre = 'Max' LIMIT 1),
 (SELECT id FROM clientes WHERE numero_documento = '10000001'),
 NULL, '2026-05-20 10:00:00', 'Chequeo general y vacunas'),
((SELECT id FROM pets WHERE nombre = 'Luna' LIMIT 1),
 (SELECT id FROM clientes WHERE numero_documento = '10000001'),
 NULL, '2026-05-22 11:00:00', 'Limpieza dental'),
((SELECT id FROM pets WHERE nombre = 'Rocky' LIMIT 1),
 (SELECT id FROM clientes WHERE numero_documento = '10000002'),
 NULL, '2026-05-25 14:00:00', 'Consulta por alergias en la piel');

-- ============================================================
-- UNIDADES
-- ============================================================
INSERT INTO units (codigo, descripcion) VALUES
('UND', 'Unidad'),
('KG', 'Kilogramos'),
('LT', 'Litros'),
('CJ', 'Cajas'),
('ML', 'Mililitros'),
('DZ', 'Docenas')
ON CONFLICT (codigo) DO NOTHING;

-- ============================================================
-- AFECTACIONES
-- ============================================================
INSERT INTO afectacion_tipos (codigo, nombre, descripcion, letra, porcentaje) VALUES
('IVA', 'Impuesto al Valor Agregado', 'Impuesto estándar del 19%', 'S', 19.00),
('EXE', 'Exento', 'Producto exento de IVA', 'E', 0.00),
('RET', 'Retención en la Fuente', 'Retención según regulación', 'R', 8.00)
ON CONFLICT (codigo) DO NOTHING;

-- ============================================================
-- PRODUCTOS
-- ============================================================
INSERT INTO productos (codigo, nombre, descripcion, unidad_id, afectacion_tipo_id, precio_unitario, stock, imagen) VALUES
('PROD001', 'Alimento Perros Premium', 'Alimento de alta calidad para perros adultos',
 (SELECT id FROM units WHERE codigo = 'UND'),
 (SELECT id FROM afectacion_tipos WHERE codigo = 'IVA'), 85000.00, 50, 'alimento-perros.jpg'),
('PROD002', 'Vitaminas para Mascotas', 'Complejo vitamínico completo',
 (SELECT id FROM units WHERE codigo = 'UND'),
 (SELECT id FROM afectacion_tipos WHERE codigo = 'IVA'), 45000.00, 30, 'vitaminas.jpg'),
('PROD003', 'Enjuague Bucal Veterinario', 'Enjuague para higiene bucal',
 (SELECT id FROM units WHERE codigo = 'KG'),
 (SELECT id FROM afectacion_tipos WHERE codigo = 'EXE'), 25000.00, 20, 'enjuague.jpg'),
('PROD004', 'Antibiótico Amoxicilina', 'Antibiótico para infecciones',
 (SELECT id FROM units WHERE codigo = 'UND'),
 (SELECT id FROM afectacion_tipos WHERE codigo = 'EXE'), 55000.00, 15, 'amoxicilina.jpg'),
('PROD005', 'Champú Medicado', 'Champú para problemas de piel',
 (SELECT id FROM units WHERE codigo = 'UND'),
 (SELECT id FROM afectacion_tipos WHERE codigo = 'IVA'), 38000.00, 40, 'champu.jpg')
ON CONFLICT (codigo) DO NOTHING;

-- ============================================================
-- COMPROBANTES
-- ============================================================
INSERT INTO comprobante_tipos (codigo, descripcion) VALUES
('FV', 'Factura de Venta'),
('FC', 'Factura de Compra'),
('NC', 'Nota de Crédito'),
('ND', 'Nota de Débito'),
('RC', 'Recibo de Caja')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO comprobante_series (comprobante_tipo_codigo, serie, correlativo) VALUES
('FV', 'F001', 1),
('FC', 'C001', 1),
('NC', 'NC01', 1),
('ND', 'ND01', 1),
('RC', 'RC01', 1)
ON CONFLICT (comprobante_tipo_codigo, serie) DO NOTHING;

-- ============================================================
-- COMPRAS
-- ============================================================
INSERT INTO compras (numero, fecha, proveedor_id, comprobante_tipo_codigo, forma_pago, estado, total) VALUES
('COMP-0001', '2026-05-10',
 (SELECT id FROM proveedores WHERE numero_documento = '800456789'),
 'FC', 'CONTADO', 'registrada', 500000.00)
ON CONFLICT (numero) DO NOTHING;

-- ============================================================
-- VENTAS
-- ============================================================
INSERT INTO ventas (numero, fecha, cliente_id, forma_pago, estado, total) VALUES
('VENT-0001', '2026-05-15',
 (SELECT id FROM clientes WHERE numero_documento = '10000001'),
 'CONTADO', 'registrada', 130000.00)
ON CONFLICT (numero) DO NOTHING;

-- ============================================================
-- CONFIGURACIÓN
-- ============================================================
INSERT INTO system_settings (setting_key, setting_value) VALUES
('app.name', 'Happy Paws'),
('app.version', '1.0.0'),
('permissions.enabled', 'true')
ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;

-- ============================================================
-- VERIFICACIÓN
-- ============================================================
SELECT 'Happy Paws - esquema compatible con Spring Boot creado correctamente' AS resultado;
