-- ============================================================
-- HAPPY PAWS - SUPABASE
-- ESQUEMA NORMALIZADO Y OPTIMIZADO
-- ============================================================
--
-- IMPORTANTE:
-- 1. Este script RECONSTRUYE las tablas.
-- 2. Se recomienda ejecutarlo en una BD nueva/desarrollo.
-- 3. Hace CASCADE sobre las tablas indicadas.
-- 4. Compras y ventas utilizan tablas de detalle.
--
-- ============================================================

BEGIN;

-- ============================================================
-- 1. LIMPIEZA
-- ============================================================

DROP TABLE IF EXISTS venta_detalles CASCADE;
DROP TABLE IF EXISTS compra_detalles CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;

DROP TABLE IF EXISTS historial_mascotas CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS pets CASCADE;

DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS compras CASCADE;

DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;

DROP TABLE IF EXISTS comprobante_series CASCADE;

DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS afectacion_tipos CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS comprobante_tipos CASCADE;
DROP TABLE IF EXISTS documento_tipos CASCADE;

DROP TABLE IF EXISTS system_settings CASCADE;


-- ============================================================
-- 2. USUARIOS
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(120) NOT NULL,

    email VARCHAR(150) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_users_name
        CHECK (TRIM(name) <> ''),

    CONSTRAINT chk_users_email
        CHECK (TRIM(email) <> '')
);


-- ============================================================
-- 3. ROLES
-- ============================================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(50) NOT NULL UNIQUE,

    description VARCHAR(150),

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_roles_name
        CHECK (TRIM(name) <> '')
);


-- ============================================================
-- 4. TIPOS DE DOCUMENTO
-- ============================================================

CREATE TABLE documento_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(50) NOT NULL UNIQUE,

    descripcion VARCHAR(255) NOT NULL,

    CONSTRAINT chk_documento_tipo_codigo
        CHECK (TRIM(codigo) <> ''),

    CONSTRAINT chk_documento_tipo_descripcion
        CHECK (TRIM(descripcion) <> '')
);


-- ============================================================
-- 5. TIPOS DE COMPROBANTE
-- ============================================================

CREATE TABLE comprobante_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(50) NOT NULL UNIQUE,

    descripcion VARCHAR(255) NOT NULL,

    CONSTRAINT chk_comprobante_tipo_codigo
        CHECK (TRIM(codigo) <> ''),

    CONSTRAINT chk_comprobante_tipo_descripcion
        CHECK (TRIM(descripcion) <> '')
);


-- ============================================================
-- 6. UNIDADES
-- ============================================================

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(50) NOT NULL UNIQUE,

    descripcion VARCHAR(255) NOT NULL,

    CONSTRAINT chk_units_codigo
        CHECK (TRIM(codigo) <> ''),

    CONSTRAINT chk_units_descripcion
        CHECK (TRIM(descripcion) <> '')
);


-- ============================================================
-- 7. TIPOS DE AFECTACIÓN
-- ============================================================

CREATE TABLE afectacion_tipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(50) NOT NULL UNIQUE,

    nombre VARCHAR(255) NOT NULL,

    descripcion VARCHAR(255) NOT NULL,

    letra VARCHAR(1) NOT NULL,

    porcentaje NUMERIC(5,2) NOT NULL DEFAULT 0,

    CONSTRAINT chk_afectacion_porcentaje
        CHECK (porcentaje >= 0 AND porcentaje <= 100),

    CONSTRAINT chk_afectacion_letra
        CHECK (TRIM(letra) <> '')
);


-- ============================================================
-- 8. MÓDULOS
-- ============================================================

CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(50) NOT NULL UNIQUE,

    name VARCHAR(100) NOT NULL,

    description VARCHAR(150),

    icon VARCHAR(100),

    route VARCHAR(255),

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    display_order INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT chk_modules_display_order
        CHECK (display_order >= 0)
);


-- ============================================================
-- 9. PERMISOS
-- ============================================================

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(100) NOT NULL UNIQUE,

    name VARCHAR(100) NOT NULL,

    description VARCHAR(150),

    action VARCHAR(30) NOT NULL,

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    module_id BIGINT NOT NULL,

    CONSTRAINT fk_permissions_module
        FOREIGN KEY (module_id)
        REFERENCES modules(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_permissions_code
        CHECK (TRIM(code) <> ''),

    CONSTRAINT chk_permissions_action
        CHECK (TRIM(action) <> '')
);


-- ============================================================
-- 10. ROLES - PERMISOS
-- ============================================================

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,

    permission_id BIGINT NOT NULL,

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================
-- 11. USUARIOS - ROLES
-- ============================================================

-- user_id es la PRIMARY KEY (no una PK compuesta con role_id):
-- esto obliga a nivel de base de datos a que un usuario nunca pueda
-- tener más de un rol asignado al mismo tiempo (coincide con
-- @UniqueConstraint(name = "uk_user_single_role") de la entidad User).
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,

    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================
-- 12. TOKENS DE RECUPERACIÓN
-- ============================================================

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token VARCHAR(255) NOT NULL UNIQUE,

    user_id BIGINT NOT NULL,

    expiry_date TIMESTAMP NOT NULL,

    used BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================
-- 13. CLIENTES
-- ============================================================

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    documento_tipo_codigo VARCHAR(50) NOT NULL,

    numero_documento VARCHAR(50) NOT NULL UNIQUE,

    razon_social VARCHAR(255) NOT NULL,

    direccion VARCHAR(255),

    telefono VARCHAR(50),

    email VARCHAR(150),

    CONSTRAINT fk_clientes_documento_tipo
        FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_clientes_documento
        CHECK (TRIM(numero_documento) <> ''),

    CONSTRAINT chk_clientes_razon_social
        CHECK (TRIM(razon_social) <> '')
);


-- ============================================================
-- 14. PROVEEDORES
-- ============================================================

CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    documento_tipo_codigo VARCHAR(50) NOT NULL,

    numero_documento VARCHAR(50) NOT NULL UNIQUE,

    razon_social VARCHAR(255) NOT NULL,

    direccion VARCHAR(255),

    telefono VARCHAR(50),

    email VARCHAR(150),

    CONSTRAINT fk_proveedores_documento_tipo
        FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_proveedores_documento
        CHECK (TRIM(numero_documento) <> ''),

    CONSTRAINT chk_proveedores_razon_social
        CHECK (TRIM(razon_social) <> '')
);


-- ============================================================
-- 15. MASCOTAS
-- ============================================================

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(120) NOT NULL,

    especie VARCHAR(80) NOT NULL,

    raza VARCHAR(80),

    edad INTEGER,

    cliente_id BIGINT NOT NULL,

    CONSTRAINT fk_pets_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_pets_nombre
        CHECK (TRIM(nombre) <> ''),

    CONSTRAINT chk_pets_especie
        CHECK (TRIM(especie) <> ''),

    CONSTRAINT chk_pets_edad
        CHECK (edad IS NULL OR edad >= 0)
);


-- ============================================================
-- 16. CITAS
-- ============================================================

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pet_id BIGINT NOT NULL,

    cliente_id BIGINT NOT NULL,

    veterinario_id BIGINT,

    fecha_hora TIMESTAMP NOT NULL,

    motivo VARCHAR(255) NOT NULL,

    CONSTRAINT fk_appointments_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_veterinario
        FOREIGN KEY (veterinario_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_appointments_motivo
        CHECK (TRIM(motivo) <> '')
);


-- ============================================================
-- 17. HISTORIAL CLÍNICO
-- ============================================================

CREATE TABLE historial_mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pet_id BIGINT NOT NULL,

    appointment_id BIGINT,

    titulo VARCHAR(150) NOT NULL,

    detalle VARCHAR(1500) NOT NULL,

    diagnostico VARCHAR(500),

    tratamiento VARCHAR(500),

    fecha_registro DATE NOT NULL,

    fecha_expiracion DATE NOT NULL,

    archivo_original VARCHAR(255),

    archivo_guardado VARCHAR(255),

    archivo_tipo VARCHAR(120),

    archivo_tamanio BIGINT,

    CONSTRAINT fk_historial_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_historial_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_historial_fechas
        CHECK (fecha_expiracion >= fecha_registro),

    CONSTRAINT chk_historial_archivo_tamanio
        CHECK (
            archivo_tamanio IS NULL
            OR archivo_tamanio >= 0
        ),

    CONSTRAINT chk_historial_titulo
        CHECK (TRIM(titulo) <> ''),

    CONSTRAINT chk_historial_detalle
        CHECK (TRIM(detalle) <> '')
);


-- ============================================================
-- 18. PRODUCTOS
-- ============================================================

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(50) NOT NULL UNIQUE,

    nombre VARCHAR(150) NOT NULL,

    descripcion VARCHAR(255),

    unidad_id BIGINT NOT NULL,

    afectacion_tipo_id BIGINT NOT NULL,

    precio_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,

    stock INTEGER NOT NULL DEFAULT 0,

    imagen VARCHAR(255),

    CONSTRAINT fk_productos_unidad
        FOREIGN KEY (unidad_id)
        REFERENCES units(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_productos_afectacion
        FOREIGN KEY (afectacion_tipo_id)
        REFERENCES afectacion_tipos(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_productos_nombre
        CHECK (TRIM(nombre) <> ''),

    CONSTRAINT chk_productos_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT chk_productos_stock
        CHECK (stock >= 0)
);


-- ============================================================
-- 19. SERIES DE COMPROBANTES
-- ============================================================

CREATE TABLE comprobante_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    comprobante_tipo_codigo VARCHAR(50) NOT NULL,

    serie VARCHAR(50) NOT NULL,

    correlativo INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_comprobante_series_tipo
        FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_comprobante_series
        UNIQUE (comprobante_tipo_codigo, serie),

    CONSTRAINT chk_comprobante_serie
        CHECK (TRIM(serie) <> ''),

    CONSTRAINT chk_comprobante_correlativo
        CHECK (correlativo >= 0)
);


-- ============================================================
-- 20. COMPRAS
-- ============================================================

CREATE TABLE compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    numero VARCHAR(20) NOT NULL UNIQUE,

    fecha DATE NOT NULL,

    proveedor_id BIGINT NOT NULL,

    comprobante_tipo_codigo VARCHAR(50) NOT NULL,

    forma_pago VARCHAR(30) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',

    total NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_compras_proveedor
        FOREIGN KEY (proveedor_id)
        REFERENCES proveedores(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_compras_comprobante_tipo
        FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compras_total
        CHECK (total >= 0),

    CONSTRAINT chk_compras_numero
        CHECK (TRIM(numero) <> ''),

    CONSTRAINT chk_compras_forma_pago
        CHECK (TRIM(forma_pago) <> ''),

    CONSTRAINT chk_compras_estado
        CHECK (TRIM(estado) <> '')
);


-- ============================================================
-- 21. DETALLE DE COMPRAS
-- ============================================================

CREATE TABLE compra_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    compra_id BIGINT NOT NULL,

    producto_id BIGINT NOT NULL,

    cantidad INTEGER NOT NULL,

    precio_unitario NUMERIC(12,2) NOT NULL,

    subtotal NUMERIC(12,2)
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_compra_detalles_compra
        FOREIGN KEY (compra_id)
        REFERENCES compras(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_compra_detalles_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compra_detalles_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_compra_detalles_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT uq_compra_producto
        UNIQUE (compra_id, producto_id)
);


-- ============================================================
-- 22. VENTAS
-- ============================================================

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    numero VARCHAR(20) NOT NULL UNIQUE,

    fecha DATE NOT NULL,

    cliente_id BIGINT NOT NULL,

    forma_pago VARCHAR(30) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',

    total NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_ventas_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_ventas_total
        CHECK (total >= 0),

    CONSTRAINT chk_ventas_numero
        CHECK (TRIM(numero) <> ''),

    CONSTRAINT chk_ventas_forma_pago
        CHECK (TRIM(forma_pago) <> ''),

    CONSTRAINT chk_ventas_estado
        CHECK (TRIM(estado) <> '')
);


-- ============================================================
-- 23. DETALLE DE VENTAS
-- ============================================================

CREATE TABLE venta_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    venta_id BIGINT NOT NULL,

    producto_id BIGINT NOT NULL,

    cantidad INTEGER NOT NULL,

    precio_unitario NUMERIC(12,2) NOT NULL,

    subtotal NUMERIC(12,2)
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_venta_detalles_venta
        FOREIGN KEY (venta_id)
        REFERENCES ventas(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_venta_detalles_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_venta_detalles_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_venta_detalles_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT uq_venta_producto
        UNIQUE (venta_id, producto_id)
);


-- ============================================================
-- 24. CONFIGURACIÓN DEL SISTEMA
-- ============================================================

CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    setting_key VARCHAR(100) NOT NULL UNIQUE,

    setting_value VARCHAR(255) NOT NULL,

    CONSTRAINT chk_system_settings_key
        CHECK (TRIM(setting_key) <> '')
);


-- ============================================================
-- 25. ÍNDICES NECESARIOS
-- ============================================================
--
-- NO se crean índices para columnas UNIQUE porque PostgreSQL
-- ya genera automáticamente esos índices.
--
-- Solo creamos índices útiles para FK y consultas frecuentes.
-- ============================================================

CREATE INDEX idx_permissions_module_id
    ON permissions(module_id);

CREATE INDEX idx_user_roles_role_id
    ON user_roles(role_id);

CREATE INDEX idx_role_permissions_permission_id
    ON role_permissions(permission_id);

CREATE INDEX idx_password_reset_tokens_user_id
    ON password_reset_tokens(user_id);

CREATE INDEX idx_password_reset_tokens_expiry_date
    ON password_reset_tokens(expiry_date);

CREATE INDEX idx_clientes_documento_tipo
    ON clientes(documento_tipo_codigo);

CREATE INDEX idx_proveedores_documento_tipo
    ON proveedores(documento_tipo_codigo);

CREATE INDEX idx_pets_cliente_id
    ON pets(cliente_id);

CREATE INDEX idx_appointments_pet_id
    ON appointments(pet_id);

CREATE INDEX idx_appointments_cliente_id
    ON appointments(cliente_id);

CREATE INDEX idx_appointments_veterinario_id
    ON appointments(veterinario_id);

CREATE INDEX idx_appointments_fecha_hora
    ON appointments(fecha_hora);

CREATE INDEX idx_historial_pet_id
    ON historial_mascotas(pet_id);

CREATE INDEX idx_historial_appointment_id
    ON historial_mascotas(appointment_id);

CREATE INDEX idx_historial_fecha_registro
    ON historial_mascotas(fecha_registro);

CREATE INDEX idx_productos_unidad_id
    ON productos(unidad_id);

CREATE INDEX idx_productos_afectacion_tipo_id
    ON productos(afectacion_tipo_id);

CREATE INDEX idx_comprobante_series_tipo
    ON comprobante_series(comprobante_tipo_codigo);

CREATE INDEX idx_compras_proveedor_id
    ON compras(proveedor_id);

CREATE INDEX idx_compras_fecha
    ON compras(fecha);

CREATE INDEX idx_compra_detalles_producto_id
    ON compra_detalles(producto_id);

CREATE INDEX idx_ventas_cliente_id
    ON ventas(cliente_id);

CREATE INDEX idx_ventas_fecha
    ON ventas(fecha);

CREATE INDEX idx_venta_detalles_producto_id
    ON venta_detalles(producto_id);


-- ============================================================
-- 26. TIPOS DE DOCUMENTO
-- ============================================================

INSERT INTO documento_tipos
(codigo, descripcion)
VALUES
('CC', 'Cedula de ciudadania'),
('NIT', 'Numero de identificacion tributaria')
ON CONFLICT (codigo) DO NOTHING;


-- ============================================================
-- 27. TIPOS DE COMPROBANTE
-- ============================================================

INSERT INTO comprobante_tipos
(codigo, descripcion)
VALUES
('FACTURA', 'Factura de venta'),
('BOLETA', 'Comprobante de venta')
ON CONFLICT (codigo) DO NOTHING;


-- ============================================================
-- 28. UNIDADES
-- ============================================================

INSERT INTO units
(codigo, descripcion)
VALUES
('NIU', 'Unidad'),
('PZA', 'Pieza')
ON CONFLICT (codigo) DO NOTHING;


-- ============================================================
-- 29. AFECTACIONES
-- ============================================================

INSERT INTO afectacion_tipos
(
    codigo,
    nombre,
    descripcion,
    letra,
    porcentaje
)
VALUES
(
    '10',
    'Gravado',
    'Gravado - Operacion onerosa',
    'G',
    18.00
),
(
    '20',
    'Exonerado',
    'Exonerado - Operacion no onerosa',
    'E',
    0.00
)
ON CONFLICT (codigo) DO NOTHING;


-- ============================================================
-- 30. ROLES
-- ============================================================

INSERT INTO roles
(name, description)
VALUES
('ADMIN', 'Administrador del sistema'),
('VETERINARIO', 'Profesional veterinario'),
('RECEPCIONISTA', 'Personal de recepcion'),
('CLIENTE', 'Cliente de la veterinaria')
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- 31. MÓDULOS
-- ============================================================

INSERT INTO modules
(
    code,
    name,
    description,
    icon,
    route,
    display_order
)
VALUES
(
    'DASHBOARD',
    'Dashboard',
    'Modulo Dashboard',
    'bi-speedometer2',
    '/dashboard',
    1
),
(
    'CITAS',
    'Citas',
    'Modulo Citas',
    'bi-calendar-check',
    '/citas',
    2
),
(
    'MASCOTAS',
    'Mascotas',
    'Modulo Mascotas',
    'bi-heart-fill',
    '/mascotas',
    3
),
(
    'CLIENTES',
    'Clientes',
    'Modulo Clientes',
    'bi-people-fill',
    '/clientes',
    4
),
(
    'PRODUCTOS',
    'Productos',
    'Modulo Productos',
    'bi-box-seam',
    '/productos',
    5
),
(
    'COMPRAS',
    'Compras',
    'Modulo Compras',
    'bi-cart-check',
    '/compras',
    6
),
(
    'VENTAS',
    'Ventas',
    'Modulo Ventas',
    'bi-cash-coin',
    '/ventas',
    7
),
(
    'PROVEEDORES',
    'Proveedores',
    'Modulo Proveedores',
    'bi-truck',
    '/proveedores',
    8
),
(
    'HISTORIAL',
    'Historial clinico',
    'Modulo Historial clinico',
    'bi-file-medical',
    '/historial',
    9
),
(
    'REPORTES',
    'Reportes',
    'Modulo Reportes',
    'bi-bar-chart',
    '/reportes',
    10
),
(
    'USUARIOS',
    'Usuarios',
    'Modulo Usuarios',
    'bi-person-gear',
    '/usuarios',
    11
),
(
    'ROLES',
    'Roles',
    'Modulo Roles',
    'bi-shield-lock',
    '/roles',
    12
),
(
    'PERMISOS',
    'Permisos',
    'Modulo Permisos',
    'bi-key',
    '/roles',
    13
),
(
    'CONFIGURACION_COMPROBANTES',
    'Configuracion de comprobantes',
    'Configuracion de comprobantes',
    'bi-receipt',
    '/configuracion',
    14
),
(
    'CONFIGURACION_DOCUMENTOS',
    'Configuracion de documentos',
    'Configuracion de documentos',
    'bi-file-text',
    '/configuracion',
    15
),
(
    'CONFIGURACION_UNIDADES',
    'Configuracion de unidades',
    'Configuracion de unidades',
    'bi-rulers',
    '/configuracion',
    16
),
(
    'CONFIGURACION_AFECTACIONES',
    'Configuracion de afectaciones',
    'Configuracion de afectaciones',
    'bi-percent',
    '/configuracion',
    17
)
ON CONFLICT (code) DO NOTHING;


-- ============================================================
-- 32. PERMISOS
-- ============================================================

INSERT INTO permissions
(
    code,
    name,
    description,
    action,
    enabled,
    module_id
)
SELECT
    x.code,
    x.code,
    x.description,
    x.action,
    TRUE,
    m.id
FROM
(
    VALUES

    ('DASHBOARD_VER',
     'Ver el dashboard',
     'VIEW',
     'DASHBOARD'),

    ('DASHBOARD_CLIENTE_VER',
     'Ver dashboard de cliente',
     'VIEW',
     'DASHBOARD'),


    ('CITAS_VER',
     'Ver citas',
     'VIEW',
     'CITAS'),

    ('CITAS_CREAR',
     'Crear citas',
     'CREATE',
     'CITAS'),

    ('CITAS_EDITAR',
     'Editar citas',
     'UPDATE',
     'CITAS'),

    ('CITAS_ELIMINAR',
     'Eliminar citas',
     'DELETE',
     'CITAS'),


    ('MASCOTAS_VER',
     'Ver mascotas',
     'VIEW',
     'MASCOTAS'),

    ('MASCOTAS_CREAR',
     'Crear mascotas',
     'CREATE',
     'MASCOTAS'),

    ('MASCOTAS_EDITAR',
     'Editar mascotas',
     'UPDATE',
     'MASCOTAS'),

    ('MASCOTAS_ELIMINAR',
     'Eliminar mascotas',
     'DELETE',
     'MASCOTAS'),


    ('CLIENTES_VER',
     'Ver clientes',
     'VIEW',
     'CLIENTES'),

    ('CLIENTES_CREAR',
     'Crear clientes',
     'CREATE',
     'CLIENTES'),

    ('CLIENTES_EDITAR',
     'Editar clientes',
     'UPDATE',
     'CLIENTES'),

    ('CLIENTES_ELIMINAR',
     'Eliminar clientes',
     'DELETE',
     'CLIENTES'),


    ('PRODUCTOS_VER',
     'Ver productos',
     'VIEW',
     'PRODUCTOS'),

    ('PRODUCTOS_CREAR',
     'Crear productos',
     'CREATE',
     'PRODUCTOS'),

    ('PRODUCTOS_EDITAR',
     'Editar productos',
     'UPDATE',
     'PRODUCTOS'),

    ('PRODUCTOS_ELIMINAR',
     'Eliminar productos',
     'DELETE',
     'PRODUCTOS'),


    ('COMPRAS_VER',
     'Ver compras',
     'VIEW',
     'COMPRAS'),

    ('COMPRAS_CREAR',
     'Crear compras',
     'CREATE',
     'COMPRAS'),

    ('COMPRAS_EDITAR',
     'Editar compras',
     'UPDATE',
     'COMPRAS'),

    ('COMPRAS_ELIMINAR',
     'Eliminar compras',
     'DELETE',
     'COMPRAS'),


    ('VENTAS_VER',
     'Ver ventas',
     'VIEW',
     'VENTAS'),

    ('VENTAS_CREAR',
     'Crear ventas',
     'CREATE',
     'VENTAS'),

    ('VENTAS_EDITAR',
     'Editar ventas',
     'UPDATE',
     'VENTAS'),

    ('VENTAS_ELIMINAR',
     'Eliminar ventas',
     'DELETE',
     'VENTAS'),


    ('PROVEEDORES_VER',
     'Ver proveedores',
     'VIEW',
     'PROVEEDORES'),

    ('PROVEEDORES_CREAR',
     'Crear proveedores',
     'CREATE',
     'PROVEEDORES'),

    ('PROVEEDORES_EDITAR',
     'Editar proveedores',
     'UPDATE',
     'PROVEEDORES'),

    ('PROVEEDORES_ELIMINAR',
     'Eliminar proveedores',
     'DELETE',
     'PROVEEDORES'),


    ('HISTORIAL_VER',
     'Ver historial clinico',
     'VIEW',
     'HISTORIAL'),

    ('HISTORIAL_CREAR',
     'Crear historial clinico',
     'CREATE',
     'HISTORIAL'),

    ('HISTORIAL_EDITAR',
     'Editar historial clinico',
     'UPDATE',
     'HISTORIAL'),

    ('HISTORIAL_ELIMINAR',
     'Eliminar historial clinico',
     'DELETE',
     'HISTORIAL'),


    ('REPORTES_VER',
     'Ver reportes',
     'VIEW',
     'REPORTES'),

    ('REPORTES_EXPORTAR',
     'Exportar reportes',
     'EXPORT',
     'REPORTES'),


    ('USUARIOS_VER',
     'Ver usuarios',
     'VIEW',
     'USUARIOS'),

    ('USUARIOS_CREAR',
     'Crear usuarios',
     'CREATE',
     'USUARIOS'),

    ('USUARIOS_EDITAR',
     'Editar usuarios',
     'UPDATE',
     'USUARIOS'),

    ('USUARIOS_ELIMINAR',
     'Eliminar usuarios',
     'DELETE',
     'USUARIOS'),


    ('ROLES_VER',
     'Ver roles',
     'VIEW',
     'ROLES'),

    ('ROLES_CREAR',
     'Crear roles',
     'CREATE',
     'ROLES'),

    ('ROLES_EDITAR',
     'Editar roles',
     'UPDATE',
     'ROLES'),

    ('ROLES_ELIMINAR',
     'Eliminar roles',
     'DELETE',
     'ROLES'),


    ('PERMISOS_VER',
     'Ver permisos',
     'VIEW',
     'ROLES'),

    ('PERMISOS_ASIGNAR',
     'Asignar permisos',
     'ASSIGN',
     'ROLES'),

    ('ROLES_ASIGNAR',
     'Asignar roles a usuarios',
     'ASSIGN',
     'ROLES'),


    ('CONFIGURACION_COMPROBANTES',
     'Administrar comprobantes',
     'VIEW',
     'CONFIGURACION_COMPROBANTES'),

    ('CONFIGURACION_DOCUMENTOS',
     'Administrar tipos de documento',
     'VIEW',
     'CONFIGURACION_DOCUMENTOS'),

    ('CONFIGURACION_UNIDADES',
     'Administrar unidades',
     'VIEW',
     'CONFIGURACION_UNIDADES'),

    ('CONFIGURACION_AFECTACIONES',
     'Administrar afectaciones',
     'VIEW',
     'CONFIGURACION_AFECTACIONES')

) AS x(code, description, action, module_code)

JOIN modules m
    ON m.code = x.module_code

ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    action = EXCLUDED.action,
    module_id = EXCLUDED.module_id,
    enabled = TRUE;


-- ============================================================
-- 33. PERMISOS DEL ADMINISTRADOR
-- ============================================================

INSERT INTO role_permissions
(
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN'

ON CONFLICT DO NOTHING;


-- ============================================================
-- 34. PERMISOS DEL VETERINARIO
-- ============================================================

INSERT INTO role_permissions
(
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM roles r

JOIN permissions p
    ON p.code IN
(
    'DASHBOARD_VER',

    'CITAS_VER',
    'CITAS_CREAR',
    'CITAS_EDITAR',

    'MASCOTAS_VER',
    'MASCOTAS_CREAR',
    'MASCOTAS_EDITAR',

    'CLIENTES_VER',

    'VENTAS_VER',
    'VENTAS_CREAR',

    'HISTORIAL_VER',
    'HISTORIAL_CREAR',
    'HISTORIAL_EDITAR',

    'REPORTES_VER',
    'REPORTES_EXPORTAR'
)

WHERE r.name = 'VETERINARIO'

ON CONFLICT DO NOTHING;


-- ============================================================
-- 35. PERMISOS DEL RECEPCIONISTA
-- ============================================================

INSERT INTO role_permissions
(
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM roles r

JOIN permissions p
    ON p.code IN
(
    'DASHBOARD_VER',

    'CITAS_VER',
    'CITAS_CREAR',
    'CITAS_EDITAR',
    'CITAS_ELIMINAR',

    'MASCOTAS_VER',
    'MASCOTAS_CREAR',
    'MASCOTAS_EDITAR',

    'CLIENTES_VER',
    'CLIENTES_CREAR',
    'CLIENTES_EDITAR',

    'PRODUCTOS_VER',
    'PRODUCTOS_CREAR',
    'PRODUCTOS_EDITAR',

    'COMPRAS_VER',
    'COMPRAS_CREAR',
    'COMPRAS_EDITAR',

    'PROVEEDORES_VER',
    'PROVEEDORES_CREAR',
    'PROVEEDORES_EDITAR',

    'VENTAS_VER',
    'VENTAS_CREAR',
    'VENTAS_EDITAR'
)

WHERE r.name = 'RECEPCIONISTA'

ON CONFLICT DO NOTHING;


-- ============================================================
-- 36. PERMISOS DEL CLIENTE
-- ============================================================

INSERT INTO role_permissions
(
    role_id,
    permission_id
)
SELECT
    r.id,
    p.id
FROM roles r

JOIN permissions p
    ON p.code IN
(
    'DASHBOARD_CLIENTE_VER',

    'CITAS_VER',
    'CITAS_CREAR',

    'MASCOTAS_VER',

    'CLIENTES_VER',

    'HISTORIAL_VER',

    'VENTAS_VER',
    'VENTAS_CREAR'
)

WHERE r.name = 'CLIENTE'

ON CONFLICT DO NOTHING;


-- ============================================================
-- 37. CONFIGURACIÓN INICIAL
-- ============================================================

INSERT INTO system_settings
(
    setting_key,
    setting_value
)
VALUES
(
    'cita.precio',
    '50.00'
)

ON CONFLICT (setting_key) DO NOTHING;


-- ============================================================
-- 38. COMPROBACIONES
-- ============================================================

COMMIT;


-- ============================================================
-- VERIFICACIÓN
-- ============================================================

SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;


-- Cantidad de permisos
SELECT
    COUNT(*) AS total_permisos
FROM permissions;


-- Permisos por rol
SELECT
    r.name AS rol,
    COUNT(rp.permission_id) AS permisos
FROM roles r
LEFT JOIN role_permissions rp
    ON rp.role_id = r.id
GROUP BY
    r.id,
    r.name
ORDER BY
    r.name;


-- Productos
SELECT
    COUNT(*) AS total_productos
FROM productos;


-- Clientes
SELECT
    COUNT(*) AS total_clientes
FROM clientes;


-- Mascotas
SELECT
    COUNT(*) AS total_mascotas
FROM pets;


-- Compras
SELECT
    COUNT(*) AS total_compras
FROM compras;


-- Ventas
SELECT
    COUNT(*) AS total_ventas
FROM ventas;
