spring.application.name=demo

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vonswlsiujblwcbkkilc
spring.datasource.password=nxN4fKua6cXAg8xJ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT_MODE:never}

app.storage.path=${APP_STORAGE_PATH:uploads}

server.port=${PORT:8080}