-- ============================================================
-- HAPPY PAWS — MIGRACIÓN ADITIVA (segura para producción)
-- ============================================================
-- A diferencia de docs/supabase-schema-corregido.sql, este script
-- NO borra ninguna tabla. Solo agrega columnas y tablas que falten,
-- usando IF NOT EXISTS en todo lo posible. Es seguro correrlo más
-- de una vez.
--
-- Soluciona puntualmente el error:
--   "Schema validation: missing column [igv] in table [ventas]"
-- y de paso verifica/crea el resto de columnas y tablas que
-- Venta.java, Compra.java, VentaDetalle.java y CompraDetalle.java
-- necesitan (subtotal/igv en compras y ventas, y las tablas
-- compra_detalles / venta_detalles).
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. ventas: agregar subtotal e igv si faltan
-- ------------------------------------------------------------

ALTER TABLE ventas
    ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE ventas
    ADD COLUMN IF NOT EXISTS igv NUMERIC(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chk_ventas_subtotal'
    ) THEN
        ALTER TABLE ventas ADD CONSTRAINT chk_ventas_subtotal CHECK (subtotal >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chk_ventas_igv'
    ) THEN
        ALTER TABLE ventas ADD CONSTRAINT chk_ventas_igv CHECK (igv >= 0);
    END IF;
END $$;

-- ------------------------------------------------------------
-- 2. compras: agregar subtotal e igv si faltan (mismo problema
--    podría existir aquí aunque el log solo mencionó ventas)
-- ------------------------------------------------------------

ALTER TABLE compras
    ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE compras
    ADD COLUMN IF NOT EXISTS igv NUMERIC(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chk_compras_subtotal'
    ) THEN
        ALTER TABLE compras ADD CONSTRAINT chk_compras_subtotal CHECK (subtotal >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chk_compras_igv'
    ) THEN
        ALTER TABLE compras ADD CONSTRAINT chk_compras_igv CHECK (igv >= 0);
    END IF;
END $$;

-- ------------------------------------------------------------
-- 3. compra_detalles: crear la tabla si no existe
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS compra_detalles (
    id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_compra_detalles_compra
        FOREIGN KEY (id_compra)
        REFERENCES compras(id_compra)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_compra_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compra_detalles_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_compra_detalles_precio CHECK (precio_unitario >= 0),

    CONSTRAINT uq_compra_producto UNIQUE (id_compra, id_producto)
);

CREATE INDEX IF NOT EXISTS idx_compra_detalles_compra ON compra_detalles(id_compra);
CREATE INDEX IF NOT EXISTS idx_compra_detalles_producto ON compra_detalles(id_producto);

-- Por si esta migración ya se había corrido antes (versión anterior sin
-- NOT NULL en la columna generada): lo corrige sin fallar si ya está bien.
ALTER TABLE compra_detalles ALTER COLUMN subtotal SET NOT NULL;

-- ------------------------------------------------------------
-- 4. venta_detalles: crear la tabla si no existe
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS venta_detalles (
    id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_venta_detalles_venta
        FOREIGN KEY (id_venta)
        REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_venta_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_venta_detalles_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_venta_detalles_precio CHECK (precio_unitario >= 0),

    CONSTRAINT uq_venta_producto UNIQUE (id_venta, id_producto)
);

CREATE INDEX IF NOT EXISTS idx_venta_detalles_venta ON venta_detalles(id_venta);
CREATE INDEX IF NOT EXISTS idx_venta_detalles_producto ON venta_detalles(id_producto);

-- Por si esta migración ya se había corrido antes (versión anterior sin
-- NOT NULL en la columna generada): lo corrige sin fallar si ya está bien.
ALTER TABLE venta_detalles ALTER COLUMN subtotal SET NOT NULL;

COMMIT;

-- ============================================================
-- COMPROBACIÓN (opcional, corre esto después para confirmar)
-- ============================================================
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name IN ('ventas', 'compras')
-- ORDER BY table_name, ordinal_position;
