-- ============================================================
-- HAPPY PAWS - Módulo de hospitalización
-- ============================================================
-- Migración ADITIVA (no reconstruye nada, segura de correr sobre una
-- base de datos ya poblada). Complementa docs/supabase-schema-corregido.sql,
-- que ya incluye este mismo cambio para instalaciones nuevas.
--
-- Agrega las tablas "hospitalizaciones" y "controles_hospitalizacion",
-- y los permisos/módulo correspondientes (HOSPITALIZACION_VER/CREAR/
-- EDITAR/ELIMINAR). Si arrancas la app después de correr esto,
-- DataInitializer va a asignar esos permisos a ADMIN (todos),
-- VETERINARIO (ver/crear/editar) y RECEPCIONISTA (solo ver)
-- automáticamente — no hace falta asignarlos a mano.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS hospitalizaciones (
    id_hospitalizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota BIGINT NOT NULL,
    jaula VARCHAR(20) NOT NULL,
    fecha_ingreso TIMESTAMP NOT NULL,
    fecha_alta TIMESTAMP,
    id_veterinario BIGINT,
    motivo_ingreso VARCHAR(500) NOT NULL,
    diagnostico_ingreso VARCHAR(500),
    tratamiento_general VARCHAR(1000),
    peso_ingreso NUMERIC(6,2),
    temperatura_ingreso NUMERIC(4,1),
    estado VARCHAR(20) NOT NULL DEFAULT 'EN_OBSERVACION',
    observaciones_alta VARCHAR(1000),

    CONSTRAINT fk_hospitalizaciones_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES pets(id_mascota)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_hospitalizaciones_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES users(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_hospitalizaciones_estado
        CHECK (estado IN ('EN_OBSERVACION','ESTABLE','CRITICO','RECUPERANDOSE','DADO_DE_ALTA','FALLECIDO')),

    CONSTRAINT chk_hospitalizaciones_peso_ingreso
        CHECK (peso_ingreso IS NULL OR peso_ingreso >= 0),

    CONSTRAINT chk_hospitalizaciones_temperatura_ingreso
        CHECK (temperatura_ingreso IS NULL OR temperatura_ingreso >= 0)
);

CREATE TABLE IF NOT EXISTS controles_hospitalizacion (
    id_control BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospitalizacion BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    peso NUMERIC(6,2),
    temperatura NUMERIC(4,1),
    frecuencia_cardiaca INTEGER,
    frecuencia_respiratoria INTEGER,
    estado_general VARCHAR(255),
    medicacion_administrada VARCHAR(500),
    observaciones VARCHAR(1000),
    id_usuario_registro BIGINT,

    CONSTRAINT fk_controles_hospitalizacion
        FOREIGN KEY (id_hospitalizacion)
        REFERENCES hospitalizaciones(id_hospitalizacion)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_controles_usuario_registro
        FOREIGN KEY (id_usuario_registro)
        REFERENCES users(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_controles_peso
        CHECK (peso IS NULL OR peso >= 0),

    CONSTRAINT chk_controles_temperatura
        CHECK (temperatura IS NULL OR temperatura >= 0)
);

CREATE INDEX IF NOT EXISTS idx_hospitalizaciones_mascota_id ON hospitalizaciones(id_mascota);
CREATE INDEX IF NOT EXISTS idx_hospitalizaciones_veterinario_id ON hospitalizaciones(id_veterinario);
CREATE INDEX IF NOT EXISTS idx_hospitalizaciones_estado ON hospitalizaciones(estado);
CREATE INDEX IF NOT EXISTS idx_hospitalizaciones_fecha_alta ON hospitalizaciones(fecha_alta);
CREATE INDEX IF NOT EXISTS idx_controles_hospitalizacion_id ON controles_hospitalizacion(id_hospitalizacion);
CREATE INDEX IF NOT EXISTS idx_controles_fecha_hora ON controles_hospitalizacion(fecha_hora);

-- ============================================================
-- Módulo y permisos (por si arrancas la app en un entorno donde
-- DataInitializer no corre automáticamente, o quieres verlos ya
-- creados antes del primer arranque)
-- ============================================================

INSERT INTO modules (code, name, description, icon, route, display_order)
VALUES ('HOSPITALIZACION', 'Hospitalizacion', 'Modulo Hospitalizacion', 'bi-hospital', '/hospitalizacion', 9)
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, name, description, action, enabled, id_modulo)
SELECT x.code, x.code, x.description, x.action, TRUE, m.id_modulo
FROM (
    VALUES
    ('HOSPITALIZACION_VER','Ver hospitalizaciones','VIEW'),
    ('HOSPITALIZACION_CREAR','Registrar ingresos a hospitalizacion','CREATE'),
    ('HOSPITALIZACION_EDITAR','Registrar controles y dar de alta','UPDATE'),
    ('HOSPITALIZACION_ELIMINAR','Eliminar hospitalizaciones','DELETE')
) AS x(code, description, action)
JOIN modules m ON m.code = 'HOSPITALIZACION'
ON CONFLICT (code) DO NOTHING;

COMMIT;
