-- HAPPY PAWS - SUPABASE
-- ESQUEMA 100% ALINEADO CON LAS ENTIDADES JPA DEL PROYECTO (verificado
-- columna por columna contra cada @Column / @JoinColumn / @JoinTable de
-- src/main/java/com/Happypaws/demo/model, agosto 2026).
--
-- Corrige respecto al script anterior:
--   * Todas las PK usan el nombre real de columna de cada entidad
--     (id_usuario, id_rol, id_modulo, id_permiso, id_cliente, id_proveedor,
--     id_mascota, id_cita, id_historial, id_producto, id_serie, id_compra,
--     id_detalle_compra, id_venta, id_detalle_venta, id_configuracion,
--     id_documento_tipo, id_comprobante_tipo, id_unidad, id_afectacion_tipo,
--     id_token) en vez de "id" genérico.
--   * FKs con el nombre real que usa cada @JoinColumn (id_modulo, id_rol,
--     id_permiso, id_usuario, id_mascota, id_cliente, id_veterinario,
--     id_cita, id_unidad, id_afectacion_tipo, id_proveedor, id_producto,
--     id_compra) en vez de module_id/role_id/permission_id/user_id/pet_id/
--     cliente_id/proveedor_id/producto_id.
--   * Se agregan las columnas "subtotal" e "igv" en "compras" (Compra.java).
--   * Se agrega la tabla "compra_detalles" (CompraDetalle.java), incluyendo
--     su columna "subtotal" GENERATED ALWAYS AS (cantidad * precio_unitario).
--   * Se agrega "venta_detalles" con la misma forma, lista para cuando el
--     módulo de Ventas reciba la misma mejora (aún no hay entidad Java para
--     ella, así que hoy no la usa ningún repositorio, pero no estorba).
--   * user_roles conserva la restricción real UNIQUE(id_usuario) definida en
--     User.java (@UniqueConstraint(name="uk_user_single_role")): cada
--     usuario solo puede tener UN rol.
--
-- IMPORTANTE: este script reconstruye las tablas del sistema.
-- Úsalo sobre una BD nueva/de desarrollo o haz backup primero.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. LIMPIEZA
-- ============================================================

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS historial_mascotas CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS venta_detalles CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS compra_detalles CASCADE;
DROP TABLE IF EXISTS compras CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS afectacion_tipos CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS comprobante_series CASCADE;
DROP TABLE IF EXISTS comprobante_tipos CASCADE;
DROP TABLE IF EXISTS documento_tipos CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- 2. TABLAS BASE
-- ============================================================

-- User.java
CREATE TABLE users (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- Role.java
CREATE TABLE roles (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150),
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- DocumentoTipo.java
CREATE TABLE documento_tipos (
    id_documento_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);

-- ComprobanteTipo.java
CREATE TABLE comprobante_tipos (
    id_comprobante_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);

-- Unidad.java (tabla física "units")
CREATE TABLE units (
    id_unidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL
);

-- AfectacionTipo.java
CREATE TABLE afectacion_tipos (
    id_afectacion_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    letra VARCHAR(1) NOT NULL,
    porcentaje NUMERIC(5,2) NOT NULL
);

-- Module.java
CREATE TABLE modules (
    id_modulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(150),
    icon VARCHAR(100),
    route VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0
);

-- ============================================================
-- 3. RBAC
-- ============================================================

-- Permission.java (@JoinColumn(name = "id_modulo"))
CREATE TABLE permissions (
    id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(150),
    action VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    id_modulo BIGINT NOT NULL,

    CONSTRAINT fk_permissions_module
        FOREIGN KEY (id_modulo)
        REFERENCES modules(id_modulo)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Role.permissions -> @JoinTable(name="role_permissions",
--   joinColumns=id_rol, inverseJoinColumns=id_permiso)
CREATE TABLE role_permissions (
    id_rol BIGINT NOT NULL,
    id_permiso BIGINT NOT NULL,

    PRIMARY KEY (id_rol, id_permiso),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (id_permiso)
        REFERENCES permissions(id_permiso)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- User.roles -> @JoinTable(name="user_roles", joinColumns=id_usuario,
--   inverseJoinColumns=id_rol, uniqueConstraints=@UniqueConstraint(
--   name="uk_user_single_role", columnNames="id_usuario"))
-- El UNIQUE(id_usuario) es real: cada usuario solo puede tener UN rol.
CREATE TABLE user_roles (
    id_usuario BIGINT NOT NULL,
    id_rol BIGINT NOT NULL,

    PRIMARY KEY (id_usuario, id_rol),

    CONSTRAINT uk_user_single_role UNIQUE (id_usuario),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (id_usuario)
        REFERENCES users(id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- PasswordResetToken.java (@JoinColumn(name = "id_usuario"))
CREATE TABLE password_reset_tokens (
    id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    id_usuario BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (id_usuario)
        REFERENCES users(id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 4. CLIENTES / PROVEEDORES
-- ============================================================

-- Cliente.java
CREATE TABLE clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_codigo VARCHAR(20) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(30),
    email VARCHAR(150),

    CONSTRAINT fk_clientes_documento_tipo
        FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- Proveedor.java
CREATE TABLE proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_codigo VARCHAR(20) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(30),
    email VARCHAR(150),

    CONSTRAINT fk_proveedores_documento_tipo
        FOREIGN KEY (documento_tipo_codigo)
        REFERENCES documento_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- 5. MASCOTAS
-- ============================================================

-- Pet.java (tabla física "pets", @JoinColumn(name = "id_cliente"))
CREATE TABLE pets (
    id_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    especie VARCHAR(80) NOT NULL,
    raza VARCHAR(80),
    edad INTEGER,
    id_cliente BIGINT NOT NULL,

    CONSTRAINT fk_pets_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 6. CITAS
-- fecha_hora es TIMESTAMP porque Appointment.java usa LocalDateTime.
-- id_veterinario apunta a users(id_usuario). Es nullable porque el
-- @JoinColumn de Appointment.java no declara nullable=false.
-- ============================================================

CREATE TABLE appointments (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota BIGINT NOT NULL,
    id_cliente BIGINT NOT NULL,
    id_veterinario BIGINT,
    fecha_hora TIMESTAMP NOT NULL,
    motivo VARCHAR(255) NOT NULL,

    CONSTRAINT fk_appointments_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES pets(id_mascota)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES users(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- ============================================================
-- 7. HISTORIAL CLÍNICO
-- ============================================================

-- HistorialMascota.java (@JoinColumn id_mascota / id_cita)
CREATE TABLE historial_mascotas (
    id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota BIGINT NOT NULL,
    id_cita BIGINT,
    titulo VARCHAR(150) NOT NULL,
    detalle VARCHAR(1500) NOT NULL,
    diagnostico VARCHAR(500),
    tratamiento VARCHAR(500),
    fecha_registro DATE NOT NULL,
    fecha_expiracion DATE NOT NULL,
    archivo_original VARCHAR(255),
    archivo_guardado VARCHAR(255),
    archivo_tipo VARCHAR(120),
    archivo_tamanio BIGINT,

    CONSTRAINT fk_historial_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES pets(id_mascota)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_historial_cita
        FOREIGN KEY (id_cita)
        REFERENCES appointments(id_cita)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- ============================================================
-- 8. PRODUCTOS
-- ============================================================

-- Producto.java (@JoinColumn id_unidad / id_afectacion_tipo)
CREATE TABLE productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    id_unidad BIGINT NOT NULL,
    id_afectacion_tipo BIGINT NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    stock INTEGER NOT NULL,
    imagen VARCHAR(255),

    CONSTRAINT fk_productos_unidad
        FOREIGN KEY (id_unidad)
        REFERENCES units(id_unidad)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_productos_afectacion
        FOREIGN KEY (id_afectacion_tipo)
        REFERENCES afectacion_tipos(id_afectacion_tipo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_productos_precio CHECK (precio_unitario >= 0),
    CONSTRAINT chk_productos_stock CHECK (stock >= 0)
);

-- ============================================================
-- 9. COMPROBANTES
-- ============================================================

-- ComprobanteSerie.java
CREATE TABLE comprobante_series (
    id_serie BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_tipo_codigo VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    correlativo INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_comprobante_series_tipo
        FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_comprobante_series_correlativo CHECK (correlativo >= 0)
);

-- ============================================================
-- 10. COMPRAS  (Compra.java)
-- Incluye subtotal / igv / total (total = subtotal + igv).
-- ============================================================

CREATE TABLE compras (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    id_proveedor BIGINT NOT NULL,
    comprobante_tipo_codigo VARCHAR(20) NOT NULL,
    forma_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_compras_proveedor
        FOREIGN KEY (id_proveedor)
        REFERENCES proveedores(id_proveedor)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_compras_comprobante_tipo
        FOREIGN KEY (comprobante_tipo_codigo)
        REFERENCES comprobante_tipos(codigo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compras_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_compras_igv CHECK (igv >= 0),
    CONSTRAINT chk_compras_total CHECK (total >= 0)
);

-- ============================================================
-- 10.1 DETALLE DE COMPRAS  (CompraDetalle.java)
-- Un producto por línea; "subtotal" es columna calculada por Postgres.
-- ============================================================

CREATE TABLE compra_detalles (
    id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_compra_detalles_compra
        FOREIGN KEY (id_compra)
        REFERENCES compras(id_compra)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_compra_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_compra_detalles_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_compra_detalles_precio CHECK (precio_unitario >= 0),

    CONSTRAINT uq_compra_producto UNIQUE (id_compra, id_producto)
);

-- ============================================================
-- 11. VENTAS  (Venta.java)
-- ============================================================

CREATE TABLE ventas (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    id_cliente BIGINT NOT NULL,
    forma_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'registrada',
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_ventas_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_ventas_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_ventas_igv CHECK (igv >= 0),
    CONSTRAINT chk_ventas_total CHECK (total >= 0)
);

-- ============================================================
-- 11.1 DETALLE DE VENTAS
-- Todavía no existe VentaDetalle.java (Ventas sigue usando un total
-- manual, igual que Compras antes de esta mejora). Se crea la tabla ya
-- alineada con la convención de nombres para cuando se replique en
-- Ventas el mismo cambio que se hizo en Compras; hoy no la usa ningún
-- repositorio y no interfiere con nada.
-- ============================================================

CREATE TABLE venta_detalles (
    id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
        GENERATED ALWAYS AS
        (cantidad * precio_unitario) STORED,

    CONSTRAINT fk_venta_detalles_venta
        FOREIGN KEY (id_venta)
        REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_venta_detalles_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_venta_detalles_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_venta_detalles_precio CHECK (precio_unitario >= 0),

    CONSTRAINT uq_venta_producto UNIQUE (id_venta, id_producto)
);

-- ============================================================
-- 12. CONFIGURACIÓN
-- ============================================================

-- SystemSetting.java
CREATE TABLE system_settings (
    id_configuracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value VARCHAR(255) NOT NULL
);

-- ============================================================
-- 13. ÍNDICES
-- ============================================================

CREATE INDEX idx_users_email ON users(email);

CREATE INDEX idx_roles_name ON roles(name);
CREATE INDEX idx_roles_enabled ON roles(enabled);

CREATE INDEX idx_permissions_module_id ON permissions(id_modulo);
CREATE INDEX idx_permissions_code ON permissions(code);
CREATE INDEX idx_permissions_action ON permissions(action);
CREATE INDEX idx_permissions_enabled ON permissions(enabled);

CREATE INDEX idx_user_roles_user_id ON user_roles(id_usuario);
CREATE INDEX idx_user_roles_role_id ON user_roles(id_rol);

CREATE INDEX idx_role_permissions_role_id ON role_permissions(id_rol);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(id_permiso);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(id_usuario);
CREATE INDEX idx_password_reset_tokens_expiry_date ON password_reset_tokens(expiry_date);

CREATE INDEX idx_clientes_numero_documento ON clientes(numero_documento);
CREATE INDEX idx_clientes_documento_tipo ON clientes(documento_tipo_codigo);

CREATE INDEX idx_proveedores_numero_documento ON proveedores(numero_documento);
CREATE INDEX idx_proveedores_documento_tipo ON proveedores(documento_tipo_codigo);

CREATE INDEX idx_pets_cliente_id ON pets(id_cliente);

CREATE INDEX idx_appointments_mascota_id ON appointments(id_mascota);
CREATE INDEX idx_appointments_cliente_id ON appointments(id_cliente);
CREATE INDEX idx_appointments_veterinario_id ON appointments(id_veterinario);
CREATE INDEX idx_appointments_fecha_hora ON appointments(fecha_hora);

CREATE INDEX idx_historial_mascota_id ON historial_mascotas(id_mascota);
CREATE INDEX idx_historial_cita_id ON historial_mascotas(id_cita);
CREATE INDEX idx_historial_fecha_registro ON historial_mascotas(fecha_registro);

CREATE INDEX idx_productos_unidad_id ON productos(id_unidad);
CREATE INDEX idx_productos_afectacion_tipo_id ON productos(id_afectacion_tipo);

CREATE INDEX idx_comprobante_series_tipo ON comprobante_series(comprobante_tipo_codigo);

CREATE INDEX idx_compras_proveedor_id ON compras(id_proveedor);
CREATE INDEX idx_compra_detalles_compra_id ON compra_detalles(id_compra);
CREATE INDEX idx_compra_detalles_producto_id ON compra_detalles(id_producto);

CREATE INDEX idx_ventas_cliente_id ON ventas(id_cliente);
CREATE INDEX idx_venta_detalles_venta_id ON venta_detalles(id_venta);
CREATE INDEX idx_venta_detalles_producto_id ON venta_detalles(id_producto);

CREATE INDEX idx_system_settings_key ON system_settings(setting_key);

-- ============================================================
-- 14. DATOS BASE UTILIZADOS POR DataInitializer
-- ============================================================

INSERT INTO documento_tipos (codigo, descripcion)
VALUES
('CC', 'Cedula de ciudadania'),
('NIT', 'Numero de identificacion tributaria')
ON CONFLICT (codigo) DO NOTHING;

-- No hay seed de comprobante_tipos en DataInitializer; estos dos son solo
-- valores de partida razonables para poder usar el módulo de Compras/Ventas
-- desde el primer arranque. Puedes editarlos/ampliarlos libremente.
INSERT INTO comprobante_tipos (codigo, descripcion)
VALUES
('FACTURA', 'Factura de venta'),
('BOLETA', 'Comprobante de venta')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO units (codigo, descripcion)
VALUES
('NIU', 'Unidad'),
('PZA', 'Pieza')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO afectacion_tipos
(codigo, nombre, descripcion, letra, porcentaje)
VALUES
('10', 'Gravado', 'Gravado - Operacion onerosa', 'G', 18.00),
('20', 'Exonerado', 'Exonerado - Operacion no onerosa', 'E', 0.00)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO roles (name, description)
VALUES
('ADMIN', 'Administrador del sistema'),
('VETERINARIO', 'Profesional veterinario'),
('RECEPCIONISTA', 'Personal de recepcion'),
('CLIENTE', 'Cliente de la veterinaria')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 15. MÓDULOS EXACTOS DE DataInitializer
-- ============================================================

INSERT INTO modules
(code, name, description, icon, route, display_order)
VALUES
('DASHBOARD', 'Dashboard', 'Modulo Dashboard', 'bi-speedometer2', '/dashboard', 1),
('CITAS', 'Citas', 'Modulo Citas', 'bi-calendar-check', '/citas', 2),
('MASCOTAS', 'Mascotas', 'Modulo Mascotas', 'bi-heart-fill', '/mascotas', 3),
('CLIENTES', 'Clientes', 'Modulo Clientes', 'bi-people-fill', '/clientes', 4),
('PRODUCTOS', 'Productos', 'Modulo Productos', 'bi-box-seam', '/productos', 5),
('COMPRAS', 'Compras', 'Modulo Compras', 'bi-cart-check', '/compras', 6),
('VENTAS', 'Ventas', 'Modulo Ventas', 'bi-cash-coin', '/ventas', 7),
('PROVEEDORES', 'Proveedores', 'Modulo Proveedores', 'bi-truck', '/proveedores', 8),
('HISTORIAL', 'Historial clinico', 'Modulo Historial clinico', 'bi-file-medical', '/historial', 9),
('REPORTES', 'Reportes', 'Modulo Reportes', 'bi-bar-chart', '/reportes', 10),
('USUARIOS', 'Usuarios', 'Modulo Usuarios', 'bi-person-gear', '/usuarios', 11),
('ROLES', 'Roles', 'Modulo Roles', 'bi-shield-lock', '/roles', 12),
('PERMISOS', 'Permisos', 'Modulo Permisos', 'bi-key', '/roles', 13),
('CONFIGURACION_COMPROBANTES', 'Configuracion de comprobantes', 'Configuracion de comprobantes', 'bi-receipt', '/configuracion', 14),
('CONFIGURACION_DOCUMENTOS', 'Configuracion de documentos', 'Configuracion de documentos', 'bi-file-text', '/configuracion', 15),
('CONFIGURACION_UNIDADES', 'Configuracion de unidades', 'Configuracion de unidades', 'bi-rulers', '/configuracion', 16),
('CONFIGURACION_AFECTACIONES', 'Configuracion de afectaciones', 'Configuracion de afectaciones', 'bi-percent', '/configuracion', 17)
ON CONFLICT (code) DO NOTHING;

-- ============================================================
-- 16. PERMISOS EXACTOS DE DataInitializer
-- ============================================================

INSERT INTO permissions (code, name, description, action, enabled, id_modulo)
SELECT x.code, x.code, x.description, x.action, TRUE, m.id_modulo
FROM (
    VALUES
    ('DASHBOARD_VER','Ver el dashboard','VIEW','DASHBOARD'),
    ('DASHBOARD_CLIENTE_VER','Ver dashboard de cliente','VIEW','DASHBOARD'),

    ('CITAS_VER','Ver citas','VIEW','CITAS'),
    ('CITAS_CREAR','Crear citas','CREATE','CITAS'),
    ('CITAS_EDITAR','Editar citas','UPDATE','CITAS'),
    ('CITAS_ELIMINAR','Eliminar citas','DELETE','CITAS'),

    ('MASCOTAS_VER','Ver mascotas','VIEW','MASCOTAS'),
    ('MASCOTAS_CREAR','Crear mascotas','CREATE','MASCOTAS'),
    ('MASCOTAS_EDITAR','Editar mascotas','UPDATE','MASCOTAS'),
    ('MASCOTAS_ELIMINAR','Eliminar mascotas','DELETE','MASCOTAS'),

    ('CLIENTES_VER','Ver clientes','VIEW','CLIENTES'),
    ('CLIENTES_CREAR','Crear clientes','CREATE','CLIENTES'),
    ('CLIENTES_EDITAR','Editar clientes','UPDATE','CLIENTES'),
    ('CLIENTES_ELIMINAR','Eliminar clientes','DELETE','CLIENTES'),

    ('PRODUCTOS_VER','Ver productos','VIEW','PRODUCTOS'),
    ('PRODUCTOS_CREAR','Crear productos','CREATE','PRODUCTOS'),
    ('PRODUCTOS_EDITAR','Editar productos','UPDATE','PRODUCTOS'),
    ('PRODUCTOS_ELIMINAR','Eliminar productos','DELETE','PRODUCTOS'),

    ('COMPRAS_VER','Ver compras','VIEW','COMPRAS'),
    ('COMPRAS_CREAR','Crear compras','CREATE','COMPRAS'),
    ('COMPRAS_EDITAR','Editar compras','UPDATE','COMPRAS'),
    ('COMPRAS_ELIMINAR','Eliminar compras','DELETE','COMPRAS'),

    ('VENTAS_VER','Ver ventas','VIEW','VENTAS'),
    ('VENTAS_CREAR','Crear ventas','CREATE','VENTAS'),
    ('VENTAS_EDITAR','Editar ventas','UPDATE','VENTAS'),
    ('VENTAS_ELIMINAR','Eliminar ventas','DELETE','VENTAS'),

    ('PROVEEDORES_VER','Ver proveedores','VIEW','PROVEEDORES'),
    ('PROVEEDORES_CREAR','Crear proveedores','CREATE','PROVEEDORES'),
    ('PROVEEDORES_EDITAR','Editar proveedores','UPDATE','PROVEEDORES'),
    ('PROVEEDORES_ELIMINAR','Eliminar proveedores','DELETE','PROVEEDORES'),

    ('HISTORIAL_VER','Ver historial clinico','VIEW','HISTORIAL'),
    ('HISTORIAL_CREAR','Crear historial clinico','CREATE','HISTORIAL'),
    ('HISTORIAL_EDITAR','Editar historial clinico','UPDATE','HISTORIAL'),
    ('HISTORIAL_ELIMINAR','Eliminar historial clinico','DELETE','HISTORIAL'),

    ('REPORTES_VER','Ver reportes','VIEW','REPORTES'),
    ('REPORTES_EXPORTAR','Exportar reportes','EXPORT','REPORTES'),

    ('USUARIOS_VER','Ver usuarios','VIEW','USUARIOS'),
    ('USUARIOS_CREAR','Crear usuarios','CREATE','USUARIOS'),
    ('USUARIOS_EDITAR','Editar usuarios','UPDATE','USUARIOS'),
    ('USUARIOS_ELIMINAR','Eliminar usuarios','DELETE','USUARIOS'),

    ('ROLES_VER','Ver roles','VIEW','ROLES'),
    ('ROLES_CREAR','Crear roles','CREATE','ROLES'),
    ('ROLES_EDITAR','Editar roles','UPDATE','ROLES'),
    ('ROLES_ELIMINAR','Eliminar roles','DELETE','ROLES'),

    ('PERMISOS_VER','Ver permisos','VIEW','ROLES'),
    ('PERMISOS_ASIGNAR','Asignar permisos','ASSIGN','ROLES'),
    ('ROLES_ASIGNAR','Asignar roles a usuarios','ASSIGN','ROLES'),

    ('CONFIGURACION_COMPROBANTES','Administrar comprobantes','VIEW','ROLES'),
    ('CONFIGURACION_DOCUMENTOS','Administrar tipos de documento','VIEW','ROLES'),
    ('CONFIGURACION_UNIDADES','Administrar unidades','VIEW','ROLES'),
    ('CONFIGURACION_AFECTACIONES','Administrar afectaciones','VIEW','ROLES')
) AS x(code, description, action, module_code)
JOIN modules m ON m.code = x.module_code
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    action = EXCLUDED.action,
    id_modulo = EXCLUDED.id_modulo,
    enabled = TRUE;

-- ============================================================
-- 17. PERMISOS POR ROL
-- DataInitializer vuelve a sincronizarlos al arrancar.
-- ============================================================

INSERT INTO role_permissions (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r
JOIN permissions p ON p.code IN (
    'DASHBOARD_VER',
    'CITAS_VER','CITAS_CREAR','CITAS_EDITAR',
    'MASCOTAS_VER','MASCOTAS_CREAR','MASCOTAS_EDITAR',
    'CLIENTES_VER',
    'PRODUCTOS_VER',
    'VENTAS_VER','VENTAS_CREAR',
    'HISTORIAL_VER','HISTORIAL_CREAR','HISTORIAL_EDITAR',
    'REPORTES_VER','REPORTES_EXPORTAR'
)
WHERE r.name = 'VETERINARIO'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r
JOIN permissions p ON p.code IN (
    'DASHBOARD_VER',
    'CITAS_VER','CITAS_CREAR','CITAS_EDITAR','CITAS_ELIMINAR',
    'MASCOTAS_VER','MASCOTAS_CREAR','MASCOTAS_EDITAR',
    'CLIENTES_VER','CLIENTES_CREAR','CLIENTES_EDITAR',
    'PRODUCTOS_VER','PRODUCTOS_CREAR','PRODUCTOS_EDITAR',
    'COMPRAS_VER','COMPRAS_CREAR','COMPRAS_EDITAR',
    'PROVEEDORES_VER','PROVEEDORES_CREAR','PROVEEDORES_EDITAR',
    'VENTAS_VER','VENTAS_CREAR','VENTAS_EDITAR'
)
WHERE r.name = 'RECEPCIONISTA'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r
JOIN permissions p ON p.code IN (
    'DASHBOARD_CLIENTE_VER',
    'CITAS_VER','CITAS_CREAR',
    'MASCOTAS_VER',
    'CLIENTES_VER',
    'HISTORIAL_VER',
    'VENTAS_VER','VENTAS_CREAR'
)
WHERE r.name = 'CLIENTE'
ON CONFLICT DO NOTHING;

-- ============================================================
-- 18. CONFIGURACIÓN INICIAL
-- ============================================================

INSERT INTO system_settings (setting_key, setting_value)
VALUES ('cita.precio', '50.00')
ON CONFLICT (setting_key) DO NOTHING;

COMMIT;

-- ============================================================
-- COMPROBACIONES (ejecutar aparte, son solo de referencia)
-- ============================================================
-- SELECT column_name, data_type
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'compras'
-- ORDER BY ordinal_position;
--
-- SELECT column_name, data_type
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'compra_detalles'
-- ORDER BY ordinal_position;
--
-- SELECT COUNT(*) AS permisos FROM permissions;
-- SELECT r.name, COUNT(rp.id_permiso) AS permisos
-- FROM roles r
-- LEFT JOIN role_permissions rp ON rp.id_rol = r.id_rol
-- GROUP BY r.id_rol, r.name
-- ORDER BY r.name;
