-- ============================================================
-- HAPPY PAWS - Ficha clínica veterinaria completa
-- ============================================================
-- Migración ADITIVA (no reconstruye nada, segura de correr sobre una
-- base de datos ya poblada). Complementa docs/supabase-schema-corregido.sql,
-- que ya incluye estos mismos cambios para instalaciones nuevas.
--
-- Agrega:
--   - Datos básicos y médicos permanentes en "pets" (sexo, fecha de
--     nacimiento, color, peso actual, foto, esterilizado, alergias,
--     enfermedades conocidas, medicamentos actuales, antecedentes,
--     observaciones).
--   - Signos vitales, examen y medicación indicada en "historial_mascotas"
--     (peso, temperatura, frecuencias, condición corporal, motivo de
--     consulta, anamnesis, examen físico, medicamento/dosis/frecuencia/
--     duración, observaciones, recomendaciones, próximo control).
--   - Tablas nuevas "vacunas" y "desparasitaciones".
--
-- Todas las columnas nuevas son NULLABLE (o con DEFAULT) para no romper
-- filas existentes. Correr como una única transacción.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. MASCOTAS (pets) - datos básicos y médicos
-- ============================================================

ALTER TABLE pets
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
    ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
    ADD COLUMN IF NOT EXISTS color VARCHAR(60),
    ADD COLUMN IF NOT EXISTS peso_actual NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS foto VARCHAR(255),
    ADD COLUMN IF NOT EXISTS esterilizado BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS alergias VARCHAR(500),
    ADD COLUMN IF NOT EXISTS enfermedades_conocidas VARCHAR(500),
    ADD COLUMN IF NOT EXISTS medicamentos_actuales VARCHAR(500),
    ADD COLUMN IF NOT EXISTS antecedentes VARCHAR(500),
    ADD COLUMN IF NOT EXISTS observaciones VARCHAR(500);

ALTER TABLE pets
    DROP CONSTRAINT IF EXISTS chk_pets_peso_actual;

ALTER TABLE pets
    ADD CONSTRAINT chk_pets_peso_actual
        CHECK (peso_actual IS NULL OR peso_actual >= 0);

-- ============================================================
-- 2. HISTORIAL CLÍNICO (historial_mascotas) - signos vitales,
--    examen y medicación indicada
-- ============================================================

ALTER TABLE historial_mascotas
    ADD COLUMN IF NOT EXISTS peso NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS temperatura NUMERIC(4,1),
    ADD COLUMN IF NOT EXISTS frecuencia_cardiaca INTEGER,
    ADD COLUMN IF NOT EXISTS frecuencia_respiratoria INTEGER,
    ADD COLUMN IF NOT EXISTS condicion_corporal INTEGER,
    ADD COLUMN IF NOT EXISTS motivo_consulta VARCHAR(255),
    ADD COLUMN IF NOT EXISTS anamnesis VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS examen_fisico VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS medicamento VARCHAR(255),
    ADD COLUMN IF NOT EXISTS dosis VARCHAR(100),
    ADD COLUMN IF NOT EXISTS frecuencia_medicamento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS duracion_tratamiento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS observaciones VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS recomendaciones VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS proximo_control DATE;

ALTER TABLE historial_mascotas
    DROP CONSTRAINT IF EXISTS chk_historial_condicion_corporal,
    DROP CONSTRAINT IF EXISTS chk_historial_peso,
    DROP CONSTRAINT IF EXISTS chk_historial_temperatura;

ALTER TABLE historial_mascotas
    ADD CONSTRAINT chk_historial_condicion_corporal
        CHECK (condicion_corporal IS NULL OR (condicion_corporal BETWEEN 1 AND 9)),
    ADD CONSTRAINT chk_historial_peso
        CHECK (peso IS NULL OR peso >= 0),
    ADD CONSTRAINT chk_historial_temperatura
        CHECK (temperatura IS NULL OR temperatura >= 0);

-- ============================================================
-- 3. VACUNAS (tabla nueva)
-- ============================================================

CREATE TABLE IF NOT EXISTS vacunas (
    id_vacuna BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    proxima_dosis DATE,
    lote VARCHAR(50),
    veterinario VARCHAR(150),

    CONSTRAINT fk_vacunas_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES pets(id_mascota)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 4. DESPARASITACIÓN (tabla nueva)
-- ============================================================

CREATE TABLE IF NOT EXISTS desparasitaciones (
    id_desparasitacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota BIGINT NOT NULL,
    producto VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    proxima_fecha DATE,
    dosis VARCHAR(50),

    CONSTRAINT fk_desparasitaciones_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES pets(id_mascota)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 5. ÍNDICES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_historial_proximo_control ON historial_mascotas(proximo_control);
CREATE INDEX IF NOT EXISTS idx_vacunas_mascota_id ON vacunas(id_mascota);
CREATE INDEX IF NOT EXISTS idx_vacunas_proxima_dosis ON vacunas(proxima_dosis);
CREATE INDEX IF NOT EXISTS idx_desparasitaciones_mascota_id ON desparasitaciones(id_mascota);
CREATE INDEX IF NOT EXISTS idx_desparasitaciones_proxima_fecha ON desparasitaciones(proxima_fecha);

COMMIT;
