-- ============================================================
-- HAPPY PAWS - Confirmación de citas por correo
-- ============================================================
-- Migración ADITIVA (no reconstruye nada, segura de correr sobre una
-- base de datos ya poblada). Complementa docs/supabase-schema-corregido.sql,
-- que ya incluye este mismo cambio para instalaciones nuevas.
--
-- Requiere que la columna appointments.estado ya exista (ver
-- docs/supabase-migration-estados-citas.sql); si tu base de datos
-- todavía no tiene esa migración aplicada, córrela primero.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS cita_confirmacion_tokens (
    id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    id_cita BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_cita_confirmacion_tokens_cita
        FOREIGN KEY (id_cita)
        REFERENCES appointments(id_cita)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cita_confirmacion_tokens_cita_id ON cita_confirmacion_tokens(id_cita);

COMMIT;
